### ISSUE TITLE
Explicit recommender training capabilities

### ISSUE THREAD

**Issue by munterkalmsteiner** [inception-project/inception#1273]
**Is your feature request related to a problem? Please describe.**
Recommenders have different training capabilities (needs). Some require training (e.g. NLP POS), some support training but work also without (e.g. string matching), some cannot be trained (e.g. concept linking). The current design does not provide fine-grained control over recommender capabilities, leading to bugs were a recommender is not marked as ready to predict, while it actually is.

**Comment by jcklie** [comment]
@reckart Is this finished now?

**Comment by reckart** [comment]
I guess so.

**Comment by reckart** [comment]
@munterkalmsteiner do you remember if there was a reason to add the `getTrainingCapability()` to the `RecommendationEngine` instead of the `RecommendationEngineFactory`? If we had it in `RecommendationEngineFactory`, then we could hide the **States used for training** settings for non-trainable recommenders.

**Comment by munterkalmsteiner** [comment]
I don't think there was a particular reason except it made sense to connect the capability query to the engine. However, I'm not sure what change you have in mind.

**Comment by reckart** [comment]
See: https://github.com/inception-project/inception/issues/1412
