### ISSUE TITLE
When using Next Page Button The lines displayed are at the buttom of the page instead of at the top

### ISSUE THREAD

**Issue by KimMontalibet** [inception-project/inception#1323]
When going to next page, the lines displayed on the screen are not the 1st one on the next page. This seems to happen only when I am at the buttom of the current page and then click on the next page. This seems to happen also when I set the display to fewer lines (20, 30, etc…).

**Comment by reckart** [comment]
Which version are you using?

**Comment by kimi40** [comment]
I am using Firefox (66.0.3) browser and I am working on Inception 10.0

**Comment by reckart** [comment]
Ok, I think what you are describing is the following:

* configure the visible rows on screen do not fit into the browser window causing a scroll bar to appear
* scroll down
* switch the next page

Expected:
* the scroll bar resets to the top of the page so that the users who was looking at the last sentences of the previous page now sees the first sentences on the next page.

Actual:
* the scroll bar stays at the current position causing the user who was looking at the last sentences of the first page to also look at the last sentences of the next page

-----

I think it may be a bit difficult to fulfill all expectations here. E.g. if a user looks at the first sentences of some page and presses the "previous page" button, the user might not expect to be directed to the last sentences of the previous page - although it is something you didn't describe, such behavior would be the logical consequence of resetting the scroll position when switching to the next page...

**Comment by reckart** [comment]
So current behavior seems to be that when switching from one page to the next, the scroll position is set top the top of the page. It happens as a soft scroll. So first the new page is rendered, then the page softly scrolls up to the first line.

Tested with 32.2-SNAPSHOT. The behavior should already have been there for quite some time now.
