### ISSUE TITLE
Adding Documentmetadata without configured layer throws NPE

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1360]
**Describe the bug**
Nullpointer Exception when trying to add a Document Metadata annotation in the Metadata Sidebar

**To Reproduce**
1. Enable document metadata with documentmetadata.enabled=true in settings.properties
2. Go to the Document Metadata Sidebar on the annotationpage
3. Click the plus sign to add a new annotation

**Expected behavior**
Catch exception.

**Screenshots**
![metadata-npe](https://user-images.githubusercontent.com/29500351/64074366-833f9680-ccaa-11e9-813c-78c448497166.png)

**Please complete the following information:**
 - Version and build ID: 0.11.0
 - OS: ubuntu
 - Browser: chrome

**Comment by reckart** [comment]
This happens when there are no metadata layers configured in the project, 

If there are no document metadata layers configured in the project, we should display in the sidebar an information that no document metadata exists and that they can be created in the project settings. We could also hide the entire sidebar if there are no document metadata layers configured in the project.

**Comment by reckart** [comment]
Covered by https://github.com/inception-project/inception/issues/2156 - if there are no document metadata layers, the metadata sidebar now won't even show anymore.
