### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by jjesusfilho** [inception-project/inception#1421]
I have a running inception docker container in a ubuntu virtual machine  and I am able to access it via browser from my local machine, but when I try to access it behind a nginx proxy, I get the following error :

`Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Sep 30 16:58:44 UTC 2019
There was an unexpected error (type=Bad Request, status=400).
Origin does not correspond to request`

**Comment by reckart** [comment]
I notice we don't seem to have included the nginx stuff in the INCEpTION documentation yet - could you please look at https://webanno.github.io/webanno/releases/3.6.0/docs/admin-guide.html#_installing_nginx and see if the info provided there helps you? WebAnno and INCEpTION both use the same deployment methods, so the WebAnno instructions should work nicely for INCEpTION as well.

**Comment by jjesusfilho** [comment]
Can you check this issue https://github.com/webanno/webanno/issues/1255
I think they have come out with a solution.  I would appreciate if you could help me with that.

**Comment by reckart** [comment]
Well, if I read it right, then the guy who reported the https://github.com/webanno/webanno/issues/1255 eventually figured out that he had entered the wrong URL into his browser. For the dockerized deployment, the URL is without `/webanno` at the end. Otherwise, I hope the documentation about nginx in WebAnno helps. If you could let me know how exactly I could further help you, I'd be happy to try.

**Comment by jjesusfilho** [comment]
In my case, when I hit https://mydomain.com/inception/login.html it opens the login page. The error message shows up after I log in.

**Comment by reckart** [comment]
Have you tried providing a `settings.properties` file to INCEpTION with the following lines (in addition to any entries you might already have there if you already have such a file):

```
wicket.core.csrf.enabled=false
wicket.core.csrf.no-origin-action=allow
wicket.core.csrf.conflicting-origin-action=allow
```

**Comment by jjesusfilho** [comment]
Yes, this is was first think I did after reading that issue. Right now it is working but through ssh tunnel.  I need to share the application with several users to start annotating.

**Comment by jjesusfilho** [comment]
Just one more question. My settings,properties file is located in the /srv/inception/db directory, created automatically when I installed the docker image. Is it right? By the way, you should correct the line to run the docker container with outside directory it is inception/inception, but it should be inceptionproj/inception.

**Comment by reckart** [comment]
The `settings.properties` file is not created automatically. You need to create it manually. Normally, it is created by the user installing the application in order to set up the connection parameters for the MySQL database. Now if you use Docker, you probably configure the DB settings via environment variables. If you follow the instructions for [storing data on the host system](https://inception-project.github.io//releases/0.12.0/docs/admin-guide.html#_storing_data_on_the_host), then the place to create the `settings.properties` file is `/srv/inception/settings.properties` on the host as explained [here](https://inception-project.github.io//releases/0.12.0/docs/admin-guide.html#_settings_file).

> By the way, you should correct the line to run the docker container with outside directory it is inception/inception, but it should be inceptionproj/inception.

Right. Thanks for pointing this out!

**Comment by jjesusfilho** [comment]
I didn't mention that I am accessing the container from a nginx installed in a network. I am figuring it out with my colleagues and pretty soon I get back to you. So don't close it, please.

**Comment by jjesusfilho** [comment]
So, the problem was with the network. I set everything in one machine and not it's working properly. Thank you.

**Comment by reckart** [comment]
I assume you mean "now it's properly working" :) Great to hear you could fix it. Is is a common problem that you hit? Something we might care to add to the documentation?
