### ISSUE TITLE
Recommender gives suggestions for already annotated tokens.

### ISSUE THREAD

**Issue by matchlesswei** [inception-project/inception#148]
As shown in the Picture, Wikinews is already annotated as NNP, but recommendation model still gives this recommendation to AL sidebar.

<img width="1027" alt="screen shot 2018-05-02 at 11 44 39" src="https://user-images.githubusercontent.com/23156705/39516815-58843f26-4dfe-11e8-9724-6915902eb0a2.png">

**Comment by matchlesswei** [comment]
According to my memory, there are some methods in the recommendation model to read the cas for getting already annotated tokens and filter these tokens so that the recommendations list doesn't contain these tokens. But I can't find them. Where are these methods or is my memory wrong? @rcffc @reckart

**Comment by rcffc** [comment]
I have removed it because it filters the predictions of existing annotations for the whole layer, but I only want to filter the predictions for existing annotations of a single feature. I moved the filtering to the RecommendationSpanRenderer code (https://github.com/inception-project/inception/pull/99/commits/418326ffff4649363e9113ff0173d1d57ee300c0).

**Comment by matchlesswei** [comment]
@reckart So I filter these annotations from cas in ALsidebar?

**Comment by reckart** [comment]
@matchlesswei @rcffc It may be a bit inefficient to filter twice: once during rendering and once in the AL. But inefficient is something we could look into a bit later. Could we at least put the filtering code into a common place and re-use it instead of re-implementing it?

**Comment by matchlesswei** [comment]
In the SpanRender, it looks like using vspan to compare:
``` 
if (isOverlapping(vspansWithoutRecommendations, ao.getOffset(), windowBegin,
                        ao.getFeature())) {
                        break;
                    }
```
But in the ALsidebar, we don't need the vspan, In the AL, just needs to `readCas`. I'm not sure for reusing it.

**Comment by betoboullosa** [comment]
I think it would make more sense keeping the filtering code in the recommendation service, and optionally providing a parameter so that the caller can enable/disable the filtering.

**Comment by reckart** [comment]
@rcffc could we move the code into a new method `Predictions.getFilteredPredictions(user, project, cas)`? We use the VDocument because it was possible and convenient, but in principle, the same code could be implemented based on the CAS and could be re-used by @matchlesswei , right?

**Comment by rcffc** [comment]
I have added a boolean parameter which turns on or off filtering. However, I cannot use this method in the RecommendationSpanRenderer because I cannot select AnnotationFS for a certain feature.

**Comment by reckart** [comment]
@rcffc but you can select AnnotationFS for a certain layer and all annotations on that layer have the feature - although it may be unset.

**Comment by rcffc** [comment]
> @rcffc but you can select AnnotationFS for a certain layer and all annotations on that layer have the feature - although it may be unset.

I don't understand what you mean. Yes, I can select AnnotationFS for a certain layer, that's what I am doing right now. Consider the case that we have annotated Barack Obama as a PERSON on the "value" feature. With the NamedEntityLinker we get the prediction "wikidata.org/entity/Q76" for the "identifier" feature but this prediction is filtered out because there already exists an annotation at this position for the NamedEntity layer.

**Comment by reckart** [comment]
I do not understand your comment then:

> However, I cannot use this method in the RecommendationSpanRenderer because I cannot select AnnotationFS for a certain feature.

**Comment by rcffc** [comment]
I assume your confusion arises from the fact that I said "I cannot use this method" ? Well actually I do.
I cannot select AnnotationFS for a certain **feature** of a given **layer**. In RecommendationSpanRenderer I am going through each VSpan and check whether the feature is already set, ergo I am just not using the parameter to filter the existing annotations in the method changed in https://github.com/inception-project/inception/commit/a9f701fdf5e25744863ce465115dd7dba725da57.

**Comment by rcffc** [comment]
In conclusion, I added a parameter for controlling whether to filter out predictions with the same start and end positions as existing annotations for a given layer. This is what Active Learning is using now. I am setting the parameter to false in RecommendationSpanRenderer, because I also need to know for which feature an existing annotation on the same position already exists.
