### ISSUE TITLE
Long annotations (e.g. sentences) don't allow lines to wrap

### ISSUE THREAD

**Issue by JackDapid** [inception-project/inception#1516]
**Describe the bug**
Long annotations (e.g. sentences) don't allow lines to wrap and thus make them unreadable.

**To Reproduce**
Annotate a long sentence.

**Expected behavior**
Very long annotations (sentences) should allow line break as otherwise the entire text becomes unreadable.

**Screenshots**
not necessary

**Please complete the following information:**
 - Version and build ID: 0.13.0
 - OS: OSX
 - Browser: Chrome

**Additional context**
Known issue in brat: https://github.com/nlplab/brat/issues/204

**Comment by reckart** [comment]
If your original texts contain line breaks, you could try switching to the "brat (line-oriented)" rendering mode in the settings dialog of the annotation page.

**Comment by JackDapid** [comment]
thanks, it is a known feature/bug of brat (see nlplab/brat#204) that annotations block line wrapping - which makes totally sense for short annotations, but renders totally unreadable if that are long annotations like from Sentence Classifier (OpenNLP Document Categorizer) - happy to look into that and see if fixable in brat (but repository seems sleeping since some years)

**Comment by reckart** [comment]
We use a meanwhile quite heavily modified version of the brat code - the JS files are here:

https://github.com/webanno/webanno/tree/master/webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource

But in principle, it would also be possible to mitigate this issue outside of the brat code. In order for the  brat visualizer to work, we need to tell it what to put into a row. E.g. the **brat (sentence-oriented)** tells brat that a row is equivalent to a sentence. The **brat (line-oriented)** tells brat that a row is equivalent to a line. It would be in principle possible to implement a mode which would create a new row after X characters and trying not to break words of course. Brat can break annotations that go across rows. So if the server "pre-wraps" the rows, you won't get these loooong annotations which are difficult to read.

Of course, finding a way to fix the issue directly in the rendering code would be nicer because then the visualisation could adapt better to the browser width.

**Comment by reckart** [comment]
"Solved" by adding a server-side wrapping which wraps at line breaks and tries to keep lines under 120 characters.

**Comment by reckart** [comment]
Needs to be activated as "Brat (wrapping)" in the annotation page preferences.
