### ISSUE TITLE
Could we measure the total time the annotator took to annotate a document?

### ISSUE THREAD

**Issue by vinayshekharcmu** [inception-project/inception#1550]
Hi 

I was wondering if there is any feature on the monitoring page that could help us measure the time that each annotator spent on a document. Or would this have to be implemented?

Thanks
Vinayshekhar

**Comment by reckart** [comment]
How do you define the time an annotator spent?

**Comment by vinayshekharcmu** [comment]
The total amount of time an annotator took to complete the annotation on a document.

**Comment by reckart** [comment]
If I started working on a document yesteday 20:00, then I got tired and today I continued and marked the document as finished at 13:00 after lunch - so that would be 17 hours?

**Comment by vinayshekharcmu** [comment]
No. What I was hoping for is the actual hours spent annotating the document. So if I spent 30 mins yesterday and 45 mins today, the total time spent on the annotation of a document would be 75 mins for this document. Is this possible to do with the current tool?

**Comment by reckart** [comment]
The issue is that you need to make assumptions as to what counts as "time spent". If a user makes an annotation and then makes the next annotation after 10 minutes - did the user require that time to make the annotation or did the user maybe fetch a coffee, have a phone call or chat with a friend.

You can check the table `logged_event` for various events including annotation actions from the user with time stamps. But you need to do your own inference as to what the significance of the time difference between two annotation actions means.

**Comment by reckart** [comment]
If you export the project, you can also check for a file called `event.log` in the exported ZIP file.

**Comment by reckart** [comment]
For curiosity: what do you need to time measure for?

**Comment by vinayshekharcmu** [comment]
Thanks Richard. I will check the file after exporting to check the amount of time spent. I will get back to you if I have any questions. 

As far as your question is concerned, I would count that the next annotation took 10 mins. We assume that the annotator will not be doing that when they are annotating.

We are trying to measure time so that we can get an estimate of how long a document takes to annotation. With this, we can kind of get a sense of the budget required to pay the annotators for our task.
