### ISSUE TITLE
Fix LAPPSGrid tests

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1599]
**Describe the bug**
Some Tests fail due to URL timeouts. 

**To Reproduce**
See Jenkis Console Log e.g.

```

[ERROR] testNerConformity(LappsGridService{name='edu.cmu.lti.oaqa.lapps.LingpipeNER - 1.1.1-SNAPSHOT', description='Lingpipe Named Entity Recognizer with model "English News: MUC-6"', url='http://vassar.lappsgrid.org/invoker/anc:lingpipe.ner_1.1.1-SNAPSHOT'}) [1](de.tudarmstadt.ukp.inception.recommendation.imls.lapps.LappsGridRecommenderConformityTest)  Time elapsed: 31.113 s  <<< ERROR!

```

**Expected behavior**
Don't run test with url unreachable.

**Comment by reckart** [comment]
@ksuderman Did you shut the services down?

**Comment by reckart** [comment]
A release won't be possible as long as these tests fail. Either they need to be fixed or disabled.

**Comment by ksuderman** [comment]
I love it when everything aligns just right to bring our house of cards crashing down...

I believe the root cause of the problem was likely two fold:
1. Vassar has been having internet issues recently
1. Our server is having hardware issues and tomcat randomly fails.  I have a new server already in the rack, it is just waiting for HDDs to be installed before I can migrate services.

Contributing factors:
1. Our health check service (https://api.lappsgrid.org/health) that "pings" all services hourly seems to have a memory leak and fails after a few days service.  Now is one of those days so it did not notify me that the Lingpipe services had gone AWOL.
1. The cron script that "pings" the health check service (running on a different server in a different location) had a bug that caused it to interpret *any* response from a service (including 404 or 500) as OK... so it did not inform me that the health check service went down.

So, I have:
1. Restarted Tomcat and the Lingpipe services are available again.  If our new server isn't ready soon I may migrate some services to Jetstream in the interim.
1. Increased the memory allocated to the HealthCheck service until I can track down the memory leak.
1. Fixed the cron script so I should be notified the next time the HealthCheck service goes down.

Sorry for the problems.

**Comment by reckart** [comment]
Thanks! We'll retest :)

**Comment by reckart** [comment]
@UWinch Are we good again?

**Comment by UWinch** [comment]
It worked for a while, but now the connection times out again.

**Comment by ksuderman** [comment]
I believe our server hardware problems may have become fatal.  I am in contact with our IT people to determine the status of the server.

- Keith

**Comment by UWinch** [comment]
It seems to be up again, thanks so much for your help @ksuderman .
