### ISSUE TITLE
Scaling inception tool for 500+ annotators

### ISSUE THREAD

**Issue by nipunsadvilkar** [inception-project/inception#1605]
First, thanks for such a great tool that provides a wide range of templates to carry out different NLP annotation exercises.

**Describe the bug**
We see Inception as an improved version of WebAnno which we had used last year to carry out annotation exercise with ~200 annotators. We are listing down the issues which we faced during the annotation exercise at scale and we would like to know your recommendations from a perspective of deployment or overall workflow.

**Our Workflow:**
We wanted 3 level QA for annotations and hence we had created two annotation projects - `project_L1`, `project_curation` so we used to export annotated charts from `project_L1` and import into `project_curation` project using API and third party python client - [pycaprio](https://pycaprio.readthedocs.io/) for L2 and L3 curation. For this import-export, we had written a wrapper around WebAnno database to see the status of files - `NEW`, `IN-PROGRESS`, `COMPLETED` at every hour to export `COMPLETED` files, import to curation project and assign to new user with `NEW` status.

**Deployment specifications**
We used AWS ECS to deploy WebAnno app (docker container) along with AWS EFS as shared storage between all docker containers and used to take a backup of it on every 6 hours.

**Issues faced**
1. After selecting new files from "Open" window selection - text files used to load slowly on the annotation editor window.

2. During NER annotation, after releasing click while selecting text to highlight, there was a lag in getting NER right-side panel to select an entity value (like PER, LOC).

3. An embedded Tomcat server crashed with following logs:
```
2019-02-12 08:53:30 INFO [annotator1] CasStorageServiceImpl - Updated annotations for user [espm1137] on document [file_1.txt](89043) in project [NER_5000](41)
2019-02-12 08:53:32 WARN [annotator1] PageAccessSynchronizer - Thread 'http-nio-8080-exec-29' failed to acquire lock to page with id '12', attempted for 1 minutes out of allowed 1 minute. The thread that holds the lock has name 'http-nio-8080-exec-118'.
2019-02-12 08:53:32 WARN [annotator1] PageAccessSynchronizer - "http-nio-8080-exec-118" daemon prio=5 tid=218808 state=RUNNABLE
2019-02-12 08:53:32 ERROR [annotator1] DefaultExceptionMapper - Unexpected error occurred
```

**Question**
1. Does hourly DB queries to check the annotation status of a file could have caused the tool to be slow? What's your opinion? 
2. Does there is a limitation for the number of users who can access the web server at a time?
3. Do you have any other suggestions to scale the app and tackle slowness? Since tool slowness causes the annotator's productivity loss and hence hampering annotation quality.
4. Is horizontal scaling preferred over vertical scaling?

**Please complete the following information:**
 - OS: Linux
 - Browser: chrome

@reckart Your suggestion would help us scale the app and make annotation exercise smooth. Thanks!

**Comment by reckart** [comment]
> Does hourly DB queries to check the annotation status of a file could have caused the tool to be slow? What's your opinion?

Hard to say - it depends on the query. The application does not (yet) create any particular indexes to make queries fast. It also depends on how exactly you exercise the query: a single SQL query or a set of queries which are controlled by some script "looping" over the DB.

> Does there is a limitation for the number of users who can access the web server at a time?

A single account must only be used from one browser - i.e. better do not try to log in with the same credentials multiple times. Other than that, Tomcat has defaults as to how many worker threads it spawns (`server.tomcat.max-threads` - see [here](https://docs.spring.io/spring-boot/docs/2.2.4.RELEASE/reference/html/appendix-application-properties.html#common-application-properties)). The default is 200 which should handle pretty high load. Other than that, concurrent access is limited by the specs of the host you run on. Mind, there is a synchronization action when loading/saving a CAS which is presently shared across all users - maybe this hits you on such a large deployment.

> Do you have any other suggestions to scale the app and tackle slowness?

What version of WebAnno have you been working with? E.g. INCEpTION should be faster than WebAnno 3.x because it already includes some optimizations from the WebAnno 4.x code.

The application does a server round-trip every time the user selects or creates an annotation. Depending on where your annotators are sitting and what kind of network connection they have, this time adds more or less to the time the server itself needs for processing.

The application currently loads and saves the annotation data on every action from the user. It would be faster if we could keep the data in memory across actions to avoid repeated loading, but that requires quite a bit of refactoring. 

The time depends on the size of your documents, number and type of annotations, etc.

If you for some reason used a beta or SNAPSHOT version, there would also be sanity checks enabled by default which can significantly slow things down.

Other than that: not without digging into the setup and profiling it.

> Since tool slowness causes the annotator's productivity loss and hence hampering annotation quality. Is horizontal scaling preferred over vertical scaling?

Again, it is hard to say without knowing more about the exact causes for your slowness.

**Comment by nipunsadvilkar** [comment]
Thanks for the prompt reply.

> It also depends on how exactly you exercise the query: a single SQL query or a set of queries which are controlled by some script "looping" over the DB.

Here is a list of queries we are querying to DB at every 1 hour: 
1. export annotated doc with `ANNOTATION_ COMPLETED` status - export api requests using pycaprio
2. Import into a new project - upload query using pycaprio
3. Iterate over list of active users for the project:
		- Randomly assigning `'NEW'` status for single user - Update query `annotation_document` table
		- `'IGNORE'` status to rest of the users - Update query `annotation_document` table

So if we say there are 20 users in a project then there are 20 update queries happening for each new file uploaded.

**Comment by reckart** [comment]
That doesn't sound like too much. How long does the procedure take until it is completed?

**Comment by nipunsadvilkar** [comment]
As it turns out by increasing heap size under [JAVA_OPTS](https://github.com/inception-project/inception/blob/cec931c0e7/inception-app-webapp/src/main/docker/Dockerfile#L32) we are seeing less crashes

**Comment by Prakshi-epi** [comment]
We are facing `PageAccessSynchronizer` errors frequently which leads to the whole application crash.
Here is the gist link for the log trace:
[PageAccessSynchronizer](https://gist.github.com/Prakshi-epi/6360d2adeef1cd60ddac305e0e0f0689)

@reckart If possible, can you please suggest the possible root cause for this behavior.

**Comment by reckart** [comment]
In this particular case, it seems that `BratRenderer.buildEntityTypes(BratRenderer.java:431)` may be taking way more time than it should. Looking at the code, I can see that it performs quite a few database requests which may become a problem in a setting with a very large number of users and potentially limited resources on the INCEpTION/database server.

When you say that this leads to a crash of the whole application, what do you mean exactly? Do you need to restart INCEpTION in order to fix the issue or is it sufficient for that one user to re-login?

Does your MySQL server have sufficient resources (cpu/memory)?

**Comment by reckart** [comment]
How many rows do you have in the `annotation_type` and the `annotation_feature` tables respectively in your DB?

**Comment by Prakshi-epi** [comment]
In the case of a Database server, we are using AWS serverless RDS as DB with the application. Also at every point, we ensure that we have 50% more capacity of the database available than an actual requirement at that point of time. 
We have a total of 90 users using this inception application.

By the **crash of whole application**, I mean that we have to restart the inception application again to bring the application up again.

**Comment by reckart** [comment]
There have been many performance improvements in the last year. I believe this issue can be considered to be resolved.
