### ISSUE TITLE
Create curation using API

### ISSUE THREAD

**Issue by jackmen** [inception-project/inception#1657]
Dear Richard,

we are currently adding the 'curation' option to pycaprio.

When I test to create curations,  I'm confronted with:

b'{"messages":[{"level":"ERROR","message":"Internal server error: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog."}]}'

I'm doing the following to provoke the error:

client.api.create_curation(project_id, document_id, annotation_format = InceptionFormat.XMI, content = io.BytesIO(annotations), document_state = 'CURATION-IN-PROGRESS')

'annotations' is the output pf pycaprio's:

annotations = client.api.annotation(project_id, document_id, 'user', annotation_format=InceptionFormat.XMI)
 

**Expected behavior**
The document should appear with its annotations and document_state 'CURATION-IN-PROGRESS' in the respective Inception project.

 - Version and build ID: INCEpTION -- 0.11.2 (2019-09-11 17:17:54, build cdd78cb18259c51647488fde393166646c7f30c7)
 - OS: [Linux]
 - Browser: [e.g. chrome]

**Additional context**
Deletion and download of curations works as expected.

Thanks a lot once again for your feedback.

Sebastian

**Comment by reckart** [comment]
I haven't looked at it in detail yet, but my hypothesis is that you actually get a ZIP file when you request the XMI format for export/download - the ZIP then contains the XMI itself and a typesystem XML file necessary to interpret the XMI. If you try to upload that ZIP again, it fails because during import, the application expects a plain XMI file. Maybe you can briefly check if this hypothesis is correct.

If it is and if you need a "plain XMI / no type-system / no ZIP" export mode, then it shouldn't be hard to add that.

**Comment by reckart** [comment]
A short-term solution for you might also be to export and re-import as binary CAS instead of XMI.

**Comment by jackmen** [comment]
Dear Richard,
thanks for your feedback. I put me on the right track. 

After unzipping the "annotations" and importing only the xmi file using:

with open('/path/to/xmi', 'rb') as f:
    xmi = f.read()

and then doing...

client.api.create_curation(project_id, document_id, annotation_format = InceptionFormat.XMI, content = io.BytesIO(xmi) , document_state = 'CURATION-IN-PROGRESS')

did the trick. 

If at some point the plain-xmi output was available, one could avoid the unzipping step. But for now it works fine this way.

Thanks a lot and have a nice Sunday evening!
