### ISSUE TITLE
IRI fields in KB edit mode should be comboboxes

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#166]
IRI fields in KB edit mode should be comboboxes so that one can conveniently switch between pre-configured IRIs or enter custom ones. Should offer the same choices as in the wizard.

![2018-05-04_16-58-32](https://user-images.githubusercontent.com/1410238/39635010-8d1dd066-4fbc-11e8-8172-4b494e7413ca.png)

**Comment by MdeBoer95** [comment]
@reckart as you already mentioned in the meeting a few weeks ago it would probably be the best to have a reusable class that contains all the textfields/comboboxes for the IRIs. So that it can be used in the wizard and in the KB edit mode, which would already solve this(#166) issue.
I commited code for this in 9c54609.
Maybe you can have short look at it because #134 and #168 are affected/depend on that change.
