### ISSUE TITLE
Impossible to create annotations via Search

### ISSUE THREAD

**Issue by llaska** [inception-project/inception#1662]
**Describe the bug**
When I try to create annotations in multiple documents, I get an error message stating that the layer is not declared.

**To Reproduce**
1. Open a document in Annotation.
a. Annotate a string with some feature.
3. Search for that string in all documents.
4. Click "Create Annotations".
5. See error "Unable to apply action to search results: Undeclared type [webanno.custom.BGsandwich]. Available types: uima.cas.TOP uima.cas.Integer uima.cas.Float uima.cas.String uima.cas.ArrayBase...", where webanno.custom.BGsandwich is the name of the layer.

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Version and build ID:  0.15.0 (2020-04-02 11:37:08, build c95448d453aee93cfaafc6a40fbe51cbe2f5728a) 
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
All layers and tagsets were imported from another project.

**Comment by llaska** [comment]
Same with  INCEpTION -- 0.15.0 (2020-04-02 11:37:08, build c95448d453aee93cfaafc6a40fbe51cbe2f5728a)

**Comment by reckart** [comment]
It sounds like this might be a recently added layer and INCEpTION has not yet upgraded all the annotation files to include it. Of course, the search/annotate action should perform such an upgrade if required, but it seems we have a bug here so that this does not happen.

As a workaround, you can try clicking yourself through all of your documents on the annotation page via the "next document" button in the action bar. Once you have opened all documents, they should have been upgraded to include your new layer and the search/annotate action should work again.
