### ISSUE TITLE
Auto logout not succeeding

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1673]
**Describe the bug**
It can happen that the auto logout feature does not succeed it logging out the user.

**To Reproduce**
1. Log in, go to some project dashboard
2. Wait for 30min (I didn't switch tabs in my browser, I just kept the window open and worked on something else)
3. When the timer runs out, one GET request is sent per second to the server, but nothing else happens. In this state, I could not go to Annotation/Curation/... anymore (it didn't let me), but clicking on Administration in the menu bar was still possible and reset the timer.

**Expected behavior**
It works.

**Please complete the following information:**
 - Version and build ID:  0.15.2 (2020-04-20 13:43:52, build 3f14b8c32e57ce44cb7f470c54307d66960a08b6)
 - OS: Ubuntu 19.10
 - Browser: FF 75.0

**Comment by reckart** [comment]
This issue causes high CPU load when the logout kicks in. Needs to be looked into.

**Comment by UWinch** [comment]
Is this still an issue? It takes a minute to log out after the timer displays **0** because the display rounds down, but after that logs out without problems for me. When exactly did the CPU load increase and how did you test that?

I tested it running the 0.15.2 jar, 0.16.x and 0.17.0 branch by reducing the logout time by setting `server.servlet.session.timeout=2m` in the settings.properties.

**Comment by reckart** [comment]
For me, the page stays with the counter at 0 and I can then see that the browser constantly tries to reload something but never manages to leave the page and take me back to the login page like it should.

**Comment by UWinch** [comment]
Hmm, are you on a specific page?

**Comment by reckart** [comment]
Don't remember. Maybe the annotation page.

**Comment by reckart** [comment]
... or the project overview or project dashboard

**Comment by UWinch** [comment]
Fixed upstream
