### ISSUE TITLE
Curation Sidebar: Should be able to change user even when finished

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1765]
**Is your feature request related to a problem? Please describe.**
Using the curation sidebar, you can change between current user and the curation user. However, when you finish a document as one of the users you should still be able to switch to the other user. Examples are cases where annotators also do curation.

**Describe the solution you'd like**
Enable the settings button even when document is finished, maybe move it to the top of the sidebar.

**Comment by lfoppiano** [comment]
I was going to open the same issue. Once there aren't document for curation it's not possible to switch back. 

Probably, leaving the settings button enabled in the panel should solve the problem. 

Also, it might happen that the user doesn't notice that he/she is editing the curation document instead of his/her annotation document. Not sure if (and how) this can be avoided, though.
