### ISSUE TITLE
Backup before curation

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1795]
**Is your feature request related to a problem? Please describe.**
Sometimes, things can go wrong during curation. It would be nice to have a way to undo it.

**Describe the solution you'd like**
Do backups, maybe when accessing the curation page, maybe with a button or before clicking on the "Merge all".

**Comment by reckart** [comment]
Is the general backup option not sufficient?

Undo is a different thing. Undo requires that there is an UI for undoing stuff. Undo should be in a separate issue - separate from backups.

**Comment by jcklie** [comment]
Regular backup could be overwritten by newer backups, so I thought seperate curation backup files would be safer

**Comment by reckart** [comment]
So what you are looking for is not really a "backup" functionality but rather some kind of "checkpoint" functionality. But I still do not understand what/when you want to create a checkpoint.

* For me, something like "undo the merge-all" operation would need to go into an "undo" issue. This seems to be a "per user" action scoped to a particular session and document.
* Something like "create a checkpoint when a certain state in the project is reached" could be interesting, but I do not know what states these are. Also, It would seem to me that this checkpointing would be an addition to a full versioning functionality - basically tagging a particular version. The question would also be then what to tag/preserve. E.g. what happens when the type system or tagset schanges after the checkpoint was created and the user tries to restore to a given checkpoint. Checkpointing seems to be a "per project" action.

**Comment by reckart** [comment]
Closing this as it is IMHO superseded by #1800
