### ISSUE TITLE
Error in importing projects

### ISSUE THREAD

**Issue by anshumandeb** [inception-project/inception#1828]
Error in importing projects when running **inceptionproject/inception:0.17.0** image. The error message in the console: `java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer`

**To Reproduce**
1. run docker image inceptionproject/inception:0.17.0
2. login as admin to the web UI
3. download the sample project Example_Concept_Linking_2019-03-26_1502.zip from https://inception-project.github.io/example-projects/
4. import the downloaded zip file using the Inception UI
5. the project is not imported 

**Expected behavior**
Sample project should be imported into Inception

**Screenshots**
NA

**Please complete the following information:**
 - inceptionproject/inception:0.17.0
 - MacOS
 - Chrome, Firefox

**Additional context**
NA

**Comment by reckart** [comment]
@anshumandeb which Java version / which JRE/JDK are you using?

**Comment by reckart** [comment]
The reason for this issue is that the INCEpTION release was made on a Java 14 (or at least something recent) instead of a Java 8.

Recent Java versions include a method `ByteBuffer flip()` method in the class `ByteBuffer` which overrides the `Buffer flip()` method in the `Buffer` class. When the code was compiled, the compiler decided to link against the co-variant version from `ByteBuffer` instead of the one from `Buffer`.
