### ISSUE TITLE
about the issue of multipersonal online collaboration 

### ISSUE THREAD

**Issue by Mozarstra** [inception-project/inception#1846]
Thanks a lot for your last reply! 
However, there are still several questions waiting for answers, I am truly hope your help.
1, how can I upload your application to my server, so that it can support multipersonal online collaboration. Particularly, I noticed that the existing version can’t support 2 accounts work via the same machine at the same time.
2, please tell me,how can I export the document in the BIO encoding fomat?

**Comment by UWinch** [comment]
Hi Mozarstra,

1. you can find information on how to set up INCEpTION on a server, so that several people have access to it in our [Admin Guide](https://inception-project.github.io/releases/0.17.1/docs/admin-guide.html)
2. all supported export formats are listed here in the [User Guide] (https://inception-project.github.io/releases/0.17.1/docs/user-guide.html#sect_formats). You can export one document from the annotation page or all documents from *Dashboard* -> *Settings* -> *Export*

I hope this is helpful to you and have fun with INCEpTION!

**Comment by Mozarstra** [comment]
thank for your reply! I think it really help me about setting up the server version.
However, I have read the export formats part of the User Guide. Sadly, I can’t figure  out which format could help me in exporting a BIO file with several costumed layers. Could you tell me, which one can realize it? Or I must use additional possession to make it?

**Comment by UWinch** [comment]
Unfortunately there is no BIO export format that supports custom layers. You could have a look at the [Webanno TSV ](https://inception-project.github.io/releases/0.17.1/docs/user-guide.html#sect_webannotsv) format which is a bit similar to BIO in that it notes the label for each token.
Alternatively, you can write a script to transfer the exported files into a format that you want. For this, the best way is to export your documents from INCEpTION as UIMA CAS XMI and use [Cassis](https://github.com/dkpro/dkpro-cassis) to process the files. However, you will need to write some python code for this.

**Comment by reckart** [comment]
Assuming the that issue was resolved as there was no more feedback and thus closing the issue.
