### ISSUE TITLE
Displaying per record metadata

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#1854]
My document consists of records from a database, each record consists of a text field and a number of metadata fields which provide additional context. There is also a parent record which contains text and additional metadata fields.

I intend on annotating spans and relations. Mostly the spans will be on the child records and the relations between spans from the same record, or to the parent.

Is there a way of presenting this in the UI? i.e. 

```
Parent Text              Parent Context
    Record 1 Text        Record 1 Context
    Record 2 Text        Record 2 Context
    Record 3 Text        Record 3 Context
...
```

or

```
Parent Text          Parent Context

Record 1 Text        Record 1 Context
Record 2 Text        Record 2 Context
Record 3 Text        Record 3 Context
...

```

There may be 10's up to may one hundred or so records per "document".

**Comment by reckart** [comment]
Assuming the plain text you imported contained line breaks that format the text in the form you represent above, you can open the preferences dialog on the annotation page (the cogwheel in the button bar above the annotation area) and switch from sentence-oriented display to line-oriented display.

**Comment by david-waterworth** [comment]
At the moment I've tokenised each record separately (and am ignoring the parent record). The context is json and isn't tokenised (the format was originally formatted for spaCy).  Wouldn't creating a single formatted text (including the context information) mean it all has to be tokenised and the annotator could accidentially annotate the context (which isn't what I want, ideally perhaps it would be a tooltip)?

**Comment by reckart** [comment]
Well, I assumed that the fixed-width font examples you made above roughly represent the layout that you would like to see on screen.

If you only want the annotators to see and work with the "text" and the "context" should only be available for infomational purposes or even for internal management, then you could do e.g. create a span layer with some string feature to hold your contextual information (even JSON) and configure the project so that this layer is not visible to the user, or visible but not editable. If you keep the layer visible, you'd also want to configure the string feature holding the JSON to not be displayed in the "bubble" on the annotation screen (untick the "visible" checkbox in the feature settings). The context would then only be available in the tooltip that shows when you hover the mouse over your context annotation bubble. However, presently all tooltip text is send from the server to the client on every render (i.e. not lazily loaded) - so if you are not on a local network with your INCEpTION server, you'd likely prefer to make the context layer not visible to the annotator in the project settings.

**Comment by reckart** [comment]
It appears as if the question could be resolved.
