### ISSUE TITLE
Recommened Docker Development Setup

### ISSUE THREAD

**Issue by malteos** [inception-project/inception#1855]
Hi all,

Thanks for your work on Inception!

What is the recommended approach for a development setup with Docker? Is it possible to mount the codebase into the Inception container and using [live reload with Spring](https://mariobuonomo.dev/blog/spring-boot-live-reload-docker)? So I do not need to rebuild the image on every code change.

I couldn't find anything on this issue in the documentation.

Best,
Malte

**Comment by jcklie** [comment]
Hi,
we have not tried such a setup yet. If you figure it out, then it would be nice if you could write a short documentation about it. INCEpTION just needs java to run, it defaults to an embedded db. Can you elaborate more why you want docker for development?
Best,

**Comment by reckart** [comment]
Best you don't use Docker but run INCEpTION as a Tomcat or Spring application directly in your IDE.

We have some instructions on how to set up Eclipse or IntelliJ: https://inception-project.github.io/releases/0.17.1/docs/developer-guide.html

I personally prefer Eclipse because I like the ability to use hot-code replacement, but the IntelliJ instructions also have some experimental ideas how to use hot-code replacement when running in IntelliJ.

**Comment by malteos** [comment]
Thanks for the pointers. I'll look into it. 

btw. I wasn't aware that a developer documentation exists. Maybe it would be good to include it as well in the dropdown menu below the admin/user guide.
