### ISSUE TITLE
[Question] annotation with Knowledge Base

### ISSUE THREAD

**Issue by ofersabo** [inception-project/inception#1907]
Hi, 

We've our own small KB. This KB is pretty simple, it has concepts and concept's subclasses. 
Each span can be assigned as either a concept or as a subclass. 

During annotation when choosing a span, the annotator wants to navigate over the KB options.
Is there a way to go over **all** the defined KB concepts and concept's subclasses? When I try this by using the arrows without providing any prefix, then no optional concepts are displayed. 

Another question regarding the KB, There are default concepts that we want to remove from the options. For example, subClassOf and SubPropertyOf. Can these be removed from the options? I.e. we want to remove them from the knowledge base.
![image](https://user-images.githubusercontent.com/31179968/103174017-68ae0b00-4867-11eb-8b8d-bbd393e96a69.png)

When I try to remove these, I get a null error, see attached image.
![Screen Shot 2020-12-27 at 17 19 12](https://user-images.githubusercontent.com/31179968/103174329-d78c6380-4869-11eb-97e4-291a2bcf60f2.png)

  
Needless to say that I skimmed the documentation at the annotation part and could not find info about that (although I might miss that)

**Comment by reckart** [comment]
There are certain properties and classes which are part of the KB mapping settings (cf. mapping section in the KB part of the project settings). If you remove properties/classes configured there... bang. We should probably add a safe-guard to prevent the user from removing stuff that is part of the mapping...

If you configure the concept feature for "classes only", then you shouldn't see any properties.

You cannot "exclude" classes or properties from a concept feature. However, you can set a "scope" in the concept feature settings - so you'd only get sub-concepts of the scope concept. You could also define one or more custom "root concepts" in the knowledge base settings. In that way, you could move all the concepts that you want users to link into a particular sub-tree of your knowledge base and limit users to choose from there either via the "root concepts" or the "scope" setting.

> When I try this by using the arrows without providing any prefix, then no optional concepts are displayed.

What is an "optional concept"? If you hit space in the concept feature editor, the dropdown should open with the first 100 concepts it finds. If you need more/less than 100, the limit can be configured as `knowledge-base.entity-linking.candidate-display-limit=XXX` in the `settings.properties` file.

**Comment by reckart** [comment]
@ofersabo actually, forget the thing about just pressing space - if you do that, you'll get concepts that the system thinks match with the annotated span text - not just the first 100 concepts. 

We could probably add a flag that the project manager could set to include the entire KB - but I would assume that KBs are normally not trivially small so that having some input cue from the user is definitely helpful/important to narrow the matching concepts down to a useful list. What is your motivation for wanting to list the entire KB in the dropdown?

**Comment by ofersabo** [comment]
Hi @reckart,

Thanks for the quick reply! 

So, I tried following your suggestions. 

Sorry, but I couldn't understand the point you raised in the first paragraph. However, the second point: configuring the concept feature for "classes only" works great 👍 . 

Setting a scope and creating a root concept seem like a good way to go with it. For now, we went with the first option, but once I try it, I'll update it here. 

FWIW, the KB definitions of classes/concepts/properties are not clear to me, I can't understand how they work together.
Is it like a relation layer? 
For example, as I wrote in a different thread, we've kind of SRL annotation project. Can we define properties that are connected to the predicate? For now we use another relation layer to map properties (A fixed set of possible properties)  to their predicate. 
If we do use these KB properties and not the relation layer then, can we limit the choice of properties to include only the ones that we inserted? I mean that I want the annotators to be able to assign properties to a predicate only if it is one of the properties that we added to the KB, and not properties like subClassOf or type.

"forget the thing about just pressing space - if you do that, you'll get concepts that the system thinks match with the annotated span text - not just the first 100 concepts."
This doesn't seem to work on my end. I hit space in the right sidebar and I get 0 results. 
see image: 
![Screen Shot 2020-12-28 at 9 08 26](https://user-images.githubusercontent.com/31179968/103196141-4c07e680-48ec-11eb-8805-c1927784b43b.png)

The final thing, it seems to me that once I work with KB the recommender feature doesn't work. Is this something you are aware of? Maybe it is for the best If we open a new ticket for that issue.

**Comment by reckart** [comment]
Classes and properties which are used of the KB mapping configuration should not be removable - and if you still do it, I have no clue what happens, but probably nothing good:

<img width="1486" alt="Screenshot 2020-12-28 at 11 00 50" src="https://user-images.githubusercontent.com/1410238/103206375-fd624880-48fb-11eb-8168-0481eae0f475.png">

One option is that you could set up two span layers and call them e.g. "Predicate" and "Argument". then you define a "Concept feature" on the "Predicate" layer and set it to allow "only properties" (because you want the predicate to correspond to a property in the KB, right?) and then you set up a "Link: Argument" feature to allow linking the arguments of the predicate to the predicate. On the "Argument" layer, you could also set up a "Concept feature" and set it to "only classes".

> If we do use these KB properties and not the relation layer then, can we limit the choice of properties to include only the ones that we inserted?

What do you mean by "ones we inserted"? If you mean that you do not want to see properties such as "subProperty" in the dropdown, then I guess it's again using scope/roots and setting up the KB such that all your custom properties are in a particular tree. Looking at our unit tests, I believe that the system should understand the idea of sub-properties and allow you to set a scope on concept features configured for "only properties" - even though the KB page does presently not display the properties as a tree but rather as a list.

> The final thing, it seems to me that once I work with KB the recommender feature doesn't work. Is this something you are aware of?

Hm, it should in principle work. E.g. if you set up a String matching recommender on a concept feature and link some word to a concept, then the system should recommend the next occurrence of that word to be linked to the same concept.

**Comment by reckart** [comment]
> "forget the thing about just pressing space - if you do that, you'll get concepts that the system thinks match with the annotated span text - not just the first 100 concepts."
> This doesn't seem to work on my end. I hit space in the right sidebar and I get 0 results.

Did you assign labels to your classes/properties in the KB? The dropdown in the concept feature editor won't work very well unless you set labels.

**Comment by reckart** [comment]
Well, from the screenshot in the first comment, I can see that labels are set at least for your custom properties (e.g. `focal_consolidation`). Mind that using the `_` here instead of a space character can have negative impact on the ability of the system to offer the item in the dropdown if you enter only a part of the label into the input field e.g. "cons".

**Comment by reckart** [comment]
A KB gives you the option organize things in a hierarchy and the ability to have richer information about things than just a simple label and description. If you do not need that power, then using a string feature with a tagset is also a good option.

**Comment by reckart** [comment]
I believe the questions here are resolved. Please create separate issues for particular feature suggestions or bugs.
