### ISSUE TITLE
Change status of annotation documents from API

### ISSUE THREAD

**Issue by ofersabo** [inception-project/inception#2048]
We work with many annotators and multiple projects on a relatively large scale.
Often, at least a few documents in a project are annotated in a way that contradicts the annotation guidelines.
Currently,  we can't check the validation of these annotations from INCEPTION. 
I don't think this is possible to validate this from the constraint feature. 

Therefore, we must download these annotations and check them on our servers with our own script. 
The issue arises when we find documents that are not valid. 
We need to re-open these documents after those were closed by the annotators when they finished.

Doing this manually is too much labor. 

Given a document ID within a project, change the file status.
for example, close or open the file for annotation.

**Comment by reckart** [comment]
Since you ask, INCEpTION indeed does have a mechanism that can invoke validators when the user tries to mark a document as finished. In principle, it would be possible to implement a custom validator in Java and hook it in there. See e.g. the `SpanCrossSentenceBehavior` class, in particular the `onValidate(...)` method.
