### ISSUE TITLE
Remote API should fail when unsupported format is requested

### ISSUE THREAD

**Issue by sandimschuh** [inception-project/inception#2070]
**Describe the bug**
When I request an annotation in HTML format via the remote API I get the annotation in the WebAnno TSV format instead of HTML.

**To Reproduce**
1. Enable the remote API in the settings.properties file
2. Open the Swagger UI
3. Select the AERO API
4. Execute a GET request for endpoint /api/aero/v1/projects/{projectId}/documents/{documentId}/annotations/{userId} with format set to HTML.
E.g. http://localhost:8080/api/aero/v1/projects/0/documents/3/annotations/admin?format=HTML
5. Klick on the "Download file" link.
6. Open the downloaded file and verify it is not a HTML file

**Expected behavior**
The downloaded file should be a HTML file and not a TSV file.

**Screenshots**
The Swagger UI
![image](https://user-images.githubusercontent.com/345385/110827036-f78ec900-8295-11eb-87e3-070f9f2172cc.png)

The downloaded file
![image](https://user-images.githubusercontent.com/345385/110827037-f8275f80-8295-11eb-8c3f-092bae0b5aac.png)

**Please complete the following information:**
 - Version and build ID: v0.18.3 build 492bf63f
 - OS: Linux
 - Browser: Microsoft Edge

**Comment by reckart** [comment]
We do not support HTML export, so it falls back to the default format. So I guess you'd prefer an error in that case instead of returning another format than requested?

**Comment by sandimschuh** [comment]
Actually, HTML would be a good way to display the annotation results for 
a document. Would it be a gread deal to implement HTML writer?
Or is ther any other format that's good for visualizing the annotations?

**Comment by reckart** [comment]
For importing HTML files, we use the DKPro Core [HtmlDocumentReader](https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-io-html-asl/src/main/java/org/dkpro/core/io/html/HtmlDocumentReader.java). The counterpart for writing files for this is [XmlDocumentWriter](https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-io-xml-asl/src/main/java/org/dkpro/core/io/xml/XmlDocumentWriter.java).

The HtmlDocumentReader takes the XML/HTML structure of the HTML file being read and represents it as annotations (annotations not visible in INCEpTION). The XmlDocumentWriter takes the annotation-encoded XML/HTML structure and writes it back into an XML (HTML) file. In this process, only the text and the XML/HTML annotations are considered. Other annotations are completely ignored because there is no guarantee that these could be aligned with the strictly hierarchical XML/HTML structure.

If you wanted to export a visualization, there would in theory be the [BratWriter](https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-io-brat-asl/src/main/java/org/dkpro/core/io/brat/BratWriter.java) but I believe you would find it very surprising and strange because the output it produces is nothing similar to the brat visualization you see in INCEpTION. This is because INCEpTION has access to additional on formation on layers and features which the DKPro Core BratWriter does not have because the additional information is part of INCEpTION and not of UIMA.

A possible idea might be to take the XmlDocumentWriter and enhance it into a HtmlDocumentWriter which would store annotations e.g. as W3C microdata while also embeddding some JavaScript to interpret that microdata and render it as highlights over the text.
