### ISSUE TITLE
[Coloring rules] tags are not colored according to the rules

### ISSUE THREAD

**Issue by ofersabo** [inception-project/inception#2137]
In our annotation project, we have a list of labels, [x, y, z], and each such label can be positive or negative.
So the tagset looks like that:
{x, x negative, y, y negative, z, z negative}

we'd like to color all negative findings in the same color, e.g. black. 

we try to use the coloring rules for that purpose, but without luck for no reason that we could understand. 

**To Reproduce**
1. import the attached project
2. try to tag some chunk as 'x negative'
3. See error - the color of the label is not as defined.
[bug__project_2021-03-24_2037.zip](https://github.com/inception-project/inception/files/6200331/bug__project_2021-03-24_2037.zip)

**Expected behavior**
label color as in the project settings. 

**Screenshots**

![image](https://user-images.githubusercontent.com/31179968/112380176-c086d180-8cf1-11eb-951d-2a602f26a9d6.png)

**Please complete the following information:**
 - 0.19.0 (2021-03-18 08:17:56, build 3f297349)
 - OSx
 -chrome

**Comment by reckart** [comment]
The pattern is a regular expression which is matched against the label. You used `negative` as the pattern which doesn not match `y negative`. In order to match "any label containing the string negative", you'd use `.*negative.*` as the pattern:

<img width="680" alt="Screenshot 2021-03-24 at 22 12 25" src="https://user-images.githubusercontent.com/1410238/112384045-3426df80-8cee-11eb-9afc-4508f7b1c57e.png">

<img width="333" alt="Screenshot 2021-03-24 at 22 14 03" src="https://user-images.githubusercontent.com/1410238/112384093-46a11900-8cee-11eb-8914-aaf40648ab49.png">

**Comment by ofersabo** [comment]
ohh, missed that. thanks :)
