### ISSUE TITLE
Allow to set Page size as Admin for a project to something higher than 5

### ISSUE THREAD

**Issue by jwijffels** [inception-project/inception#2233]
**Is your feature request related to a problem? Please describe.**
I'm trying to switch the use of BRAT to Inception for annotating text based on this project: https://en.getuigenissen.org. 
The texts are 18th-19th century transcriptions and are generally about 30-50 sentences long. We plan to use volunteers for this but I'm afraid the volunteers will not see with that the text is longer than 5 sentences as the default Page Size is 5

**Describe the solution you'd like**
I would like to have the option to define the default Page Size upfront as a Project setting such that I can set it higher immediately for all annotations.

**Describe alternatives you've considered**
None

**Additional context**
See above
![Knipsel](https://user-images.githubusercontent.com/1710810/116214947-802ecf00-a747-11eb-96dd-e848dc91e5ee.PNG)

**Comment by reckart** [comment]
You can set `annotation.default-preferences.pageSize=100` in the `settings.properties` file.

Mind that a large page size will significantly slow down the reaction time in the browser because the browser-side rendering process takes longer. I'd recommend maybe a size of 20-25 at most - but you need to try out what is still acceptable for you and your users.

**Comment by jwijffels** [comment]
Ah, thanks. So it's a system wide setting. Fine for me as well currently. 
I must have overlooked this setting when skimming the documentation. 
Thank you for the help.
