### ISSUE TITLE
Sentense split error when comes to tokens like U.S.  

### ISSUE THREAD

**Issue by FajunChen** [inception-project/inception#2265]
**Describe the bug**
When processing corpus including tokens like U.S., the system fails to split sentenses correctly. 

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Annotation'
3. Choose a text file form documents
3. Click on 'Open'
4. If there exists tokens like U.S., you would see the error

**Expected behavior**
Most of the time, 'U.S.' is just a token in the middle of a sentense,  the sentense should not end up after it.

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 0.19.3 (2021-04-25 09:58:11, build 238b0e91)
 - OS: OS X
 - Browser: chrome

**Additional context**

**Comment by jcklie** [comment]
INCEpTION internall uses the [Java BreakIterator](https://docs.oracle.com/javase/7/docs/api/java/text/BreakIterator.html) to split tokens. If you need a better tokenizer, then you would do that outside of INCEpTION and then import a document that is already pretokenized. For example, you could use [this notebook](https://colab.research.google.com/github/inception-project/inception/blob/master/notebooks/using_pretokenized_and_preannotated_text.ipynb) that uses spacy for that.

**Comment by reckart** [comment]
I think we should maybe consider what needs to be done to switch to or support a alternative tokenizers... maybe [JTok](https://github.com/DFKI-MLT/JTok).

**Comment by jcklie** [comment]
JTok  is GNU . We would then still have the problem that there are languages for which we do not have good tokenizers, e.g. Chinese or Japanese. I think it would be better to have a simple format that allows pretokenizaton.

**Comment by reckart** [comment]
JTok is **L**GPL.

**Comment by reckart** [comment]
Well, we have `PretokenizedTextFormatSupport` (Plain text (space-separated tokens, one sentence per line))

**Comment by jcklie** [comment]
That is only for sentences, I thought we also needed one for tokens, e.g. a stripped down Conll2003 with just the tokens.

**Comment by reckart** [comment]
It is also for tokens which must be "space separated".

**Comment by FajunChen** [comment]
INCEpTION is an annotation support platform. How about leave the tokenization or sentence splitting functions to recommendations or other pluggable modules? That is, make all annotation user interfaces to be character-based, let users to mark the token/sentence boundaries if required.

**Comment by reckart** [comment]
The concepts of sentence and token are used quite pervasively throughout the tool. E.g. in order to configure "token-level" annotations, you obviously need to know what a "token" actually is. And depending on the task, it can be very helpful to have a pre-tokenized and pre-sentenceplit setup.

That said, we are working towards making this more flexible. Quite recently, e.g. the visualiszation was largely decoupled from the presence of sentence and token (there is still the "sentence-oriented" view and it is still the default, but there are alternatives now!). We also are working towards allowing to actually treat tokens and sentences as annotation layers: https://github.com/inception-project/inception/pull/2141

It will take a while until we get there.

Meanwhile, if you make a few concessions, you can more or less do what you describe:

- Create a new project e.g. using the "Span/relation" quick template. 
- Change the layers to character-level granularity
- Add any other layers you want at character granularity
- Make sure that "cross sentence" is enabled on any of the layers you create

However, if you do that, you'll lose the ability to use most of the recommenders because they generate their training data from sentence-level samples (in some cases, this could be adjusted). They also ensure that suggestions respect token/sentence boundaries. Also, the WebAnno TSV export format won't be very useful anymore in this scenario, but we recommend using UIMA CAS XMI anyway.

**Comment by FajunChen** [comment]
I like the idea of treating tokens and sentences as annotation layers. NLP steps as a set of procedures may be combined in different ways.  It not easy to make the tool both flexible and handy to use. Advanced architecture and elegant ui design are requried.

**Comment by reckart** [comment]
> It not easy to make the tool both flexible and handy to use.

Yep! But we try nevertheless 😸
