### ISSUE TITLE
Tutorial UI elements sometimes clog up in top-left corner

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#2310]
The collapsed sidebar works. But when clicking through the tutorial, sometimes it ended up in a strange situation for me with the UI elements of the tutorial clogging up in the top-left corner of the screen.

<img width="234" alt="Screenshot 2021-05-21 at 22 04 18" src="https://user-images.githubusercontent.com/1410238/119192562-a6166d80-ba80-11eb-94e4-dafbea780bcf.png">

_Originally posted by @reckart in https://github.com/inception-project/inception/issues/2284#issuecomment-846224493_

**Comment by reckart** [comment]
@UWinch any idea?

**Comment by UWinch** [comment]
I think this happens when the element that should be selected for the current tutorial step cannot be found. Does this happen for you at specific times or seemingly random? I will also see if there is a way to handle these types of errors, maybe we can catch them and show an error message, so we have some graceful way to stop the tutorial in these cases. But not sure yet how this might work with the library we use.

**Comment by reckart** [comment]
It seemed to happen randomly. First time it happened on one page (don't remember which), then I restarted, got past that point and then it happened on a later page again.

Maybe the script executes too early while the page is still being constructed?

**Comment by reckart** [comment]
Ok, so this happens when at the last step of the tutorial I directly go to the annotation page instead of clicking on "Thanks".
