### ISSUE TITLE
Displayed Text changes as annotations are added / removed

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2466]
I've been experimenting with different ways of tokenisation. In particular whether to treat separators such as '.', '-' and '_' as tokens or whitespace. For example `3PS-PAC-13-03_RmCO2` can be tokenised as `3PS` `PAC` `13` `03` `Rm` `CO2` or `3PS` `-` `PAC` `-` `13` `-` `03` `_` `Rm` `CO2`

The issue I've run into is inception seems to display text from annotation spans. So by default, it displays the text of all tokens, along with whitespace (where _ seems to be treated as whitespace but other punctuation  isn't) i.e.

`3PSPAC1303_RmCO2` or `3PS-PAC-13-03_RmCO2`

However, as soon as I add an annotation the rule then also covers this annotation - so in the former case the display changes to

`3PSPAC-13-03_RmCO2`

I can 'fix' this either by ensuring that the tokenisation matches exactly the rules expected by inception, or adding a layer with annotations at the sentence level (i.e. spans which cover each sentence) which force them to display correctly. If I change my tokenisation, it's not optimal for my model - the separators actually increase perplexity. I can work around this by tagging them as whitespace tokens like spacy does I guess (so my model datareader can skip them). But I'm not sure I can add additional features to a `de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Token` and I've not checked if I create a new subType does inception still treat the subType as type Token?

Also it makes it harder to users to correctly tag spans since these characters shouldn't be selectable.

If I use sentence spans it works but it clutters the UI (and they can be disabled by the user).

Ideally I feel that if there is a sentence span over text, that text would be displayed verbatim. The sentence spans seem to be treated differently to annotation spans, despite `de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Sentence` and `de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Token` both having super type `uima.tcas.Annotation`.

**Comment by reckart** [comment]
Hm, so my understanding is that you have certain characters that you do want to render but you do not want them to be part of annotations. I am not sure how exactly your annotators annotate.... but I think if I wanted to model something to do what I believe you want to do, then it would be this:

* tokenize the text normally such that every non-whitespace character is covered by a token (i.e. `3PS - PAC - 13 - 03 _ Rm CO2`)
* after exporting the annotated documents (or when handling the text in a external recommender) trim the annotations such that any tokens that are exactly the characters you want to ignore are removed from them.

You cannot add additional features to Token (or to any other built-in layers) so far, but I didn't really get why you want to do that. 

Subtyping is supported in UIMA, but INCEpTION is not set up to properly handle subtyping - it expects that there is a flat non-hierarchical set of layers.

Maybe you can explain a bit more what your context is any why you are trying to do what you are doing.

**Comment by david-waterworth** [comment]
Thanks, I'll probably use the workaround you suggest. However, what I don't understand is why the Sentence span doesn't behave in the same manner as a custom span. For example

I tokenise `3PS-PAC-13-03_RmCO2` as `3PS` `PAC` `13` `03` `Rm` `CO2` and create a sentence that exactly aligns with the start of token 1 and end of token 6. This displays

3PSPAC1303_RmCO2

There seems to be a slightly arbitrary choice as to what non-tokenised text is displayed and what isn't (the _ character is displayed, the others aren't).

I then create a custom layer with sentence alignment and create another span that is identical to the sentence span, i.e. starts on the first and last character of each sentance. When this layer is enabled the remaining non-token text is also displayed, i.e.

3PS-PAC-13-03_RmCO2

When it is disabled it reverts to the original render.

If I could simply enable the same logic that applies to span layers to the sentence layer, I feel like the text would display correctly without having to post-filter tokens or create a special layer.

**Comment by reckart** [comment]
Am Sa., 10. Juli 2021 um 00:54 Uhr schrieb David Waterworth <
***@***.***>:

> If I could simply enable the same logic that applies to span layers to the
> sentence layer, I feel like the text would display correctly without having
> to post-filter tokens or create a special layer.
>
If you annotate each token individually, maybe yes.

If you annotate multiple tokens, probably no because a span annotation is
defined in terms of a character start/end position and not in terms of a
list of tokens. So at least you would have to manually extract all the
tokens covered by your annotation. If you do that, you could also just
create another custom layer say "Relevant" and annotate relevant words with
that in a pre-processing step before importing. But technically easier is
you remove the undesired tokens in a post-processing step.

I don't know exactly how the brat renderer works in this special situation.
If you have a long span, then the brat renderer is unable to break this
long span into parts. It also no longer inserts dynamic spacing between
annotations to accommodate for reations or wide "bubbles". So in that case,
it probably first considers the widest annotation and its text and
afterwards fits the smaller annotations on top of it. If there is no wide
multi-token annotation, then brat inserts spacing between tokens to avoid
needless stacking of annotation bubbles and to give space to relation arcs.
But then it assumes that there is actually no text anymore between the
tokens.

Probably the "proper" way to approach this is to have a separate
tokenization scheme only for rendering instead of using the "real" backend
tokens. That is what we started doing in the "editable tokens" branch -
because if we want the user to be able to actually see and modify token
boundaries, then they cannot be used as a basis for rendering.

-- Richard

**Comment by reckart** [comment]
I have added a PR which decouples the brat rendering from the Token annotation. Would you like to provide a little test project or test file to check if it works as you expect?

**Comment by david-waterworth** [comment]
I've attached an xmi that contains two Sentence annotations. The tokens don't cover the -._ characters but these should still be displayed in the UI.

Sentences are delimited by \n but these characters are not covered by annotations (they're intended so that I can display multiple records in either sentence or line modes).

[2466.xmi.zip](https://github.com/inception-project/inception/files/6797836/2466.xmi.zip)

**Comment by reckart** [comment]
![Screenshot 2021-07-16 at 19 06 57](https://user-images.githubusercontent.com/1410238/125984023-2a30e3b7-6e4d-447c-aecd-11bdcdd5534f.png)

Does this look good?

**Comment by reckart** [comment]
Note that even if this renders good, there could be all kinds of issues coming up at a later stage due to the "missing" tokens - those issues would need to be discovered and fixed separately.

**Comment by david-waterworth** [comment]
@reckart yes that looks good. I've been using tokens that don't cover the entire text for a while (but with a separate annotation layer covering each sentence to force it to display properly) and haven't observed any other issues. 

It would be nice though to be able to both tokeniser all characters and also prevent certain characters from being selectable as the start/end of an annotation. 

For example, the spacy doc API (https://spacy.io/api/doc) for every token in the words array if the corresponding entry in the spaces array is False you cannot end a span on that token. So in Prodigy if I create a Doc as follows the tokens cover all the text and you cannot start/end a span on - or _ (actual whitespace is explicitly excluded). This does actually render a space after each word token though so it's still a workaround.

PAC		True
-		False
13		True	
-		False		
03		True	
_		False
Rm		True	
CO2		True
