### ISSUE TITLE
Add a language field to the KnowledgeBase and KBObject

### ISSUE THREAD

**Issue by rcffc** [inception-project/inception#263]
Make it possible to define default language for a Knowledge Base in the settings. This default language dictates in which language the label and description of instances/concepts/relations are retrieved.

**Comment by reckart** [comment]
@rcffc please add a proper description to this issue

**Comment by naveen2507** [comment]
@rcffc Can you please update on the status of this issue?

**Comment by rcffc** [comment]
@naveen2507 I have finished it, maybe you want to review it?

**Comment by reckart** [comment]
@naveen2507 @MdeBoer95 as part of this, a configuration settings for the "default language" is introduced in the KB settings. We could also use that setting to control for which language we retrieve the labels. That is, instead of the currently hard-coded `en`, we would use the new settings from the KB.

That would alleviate the problem reported in #443 since the user can at least select which language she wants to work with.

It doesn't really fix #443 though because there could still be the case that a KB comes with multiple languages and there is no label available in the setting configured in the KB. In that case, it would still probably be good to select some other label instead of the IRI. We should discuss this in #443.

@rcffc Could you please extend the this PR to also use the language from the KB in the queries instead of the hard-coded `en`?

**Comment by rcffc** [comment]
> @rcffc  Could you please extend the this PR to also use the language from the KB in the queries instead of the hard-coded en?

Ok should be done now.
