### ISSUE TITLE
Make finish document use a checkmark instead of a lock

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2675]
**Is your feature request related to a problem? Please describe.**
Finishing a document for a user is about finishing, not locking, so the icon is maybe unclear.

**Describe the solution you'd like**
Use a checkmark instead and change the tooltip

**Comment by reckart** [comment]
So the icon serves a double-purpose. It shows the current state and it toggles the state. So if the icon for finishing is a checkmark, what should the icon turn into when the document has finished?

That said, the icon for finishing a document in the dynamic workload mode **is** a checkmark because in that mode, there is no double-function. Clicking on the button finishes the document and takes you to the next and there is no way to go back.
