### ISSUE TITLE
Annotating call records

### ISSUE THREAD

**Issue by WilliamQue** [inception-project/inception#2842]
I'm annotating call records between salesmen and customers, the documents are like:

salesman01: Hello, happy new year! what can I do for you?
customer01: Happy new year, I'm to buy a SUV.
salesman01: Which car series do you prefer?
customer01: Not sure, perhaps BMW X3.
...

Now I have to add speaker(salesman01/customer01)  at the beginning of the line to distinguish who said it.

Is there a better way to avoid doing this? for example, we can add a self-defined column(called speaker) in the annotation area, or just replace sentence id with speaker.

**Comment by reckart** [comment]
There are no provisions at the moment for adding additional columns in the brat-based editor.

What I usually advice is either to start the sentences with `salesman01:` and simply not annotate it - or to pre-annotate the texts before import with a zero-width annotation at the beginning of a sentence that indicates the speaker.

**Comment by reckart** [comment]
Similar functionality can be realized now using an editor plugin, e.g. https://github.com/inception-project/inception-annotatorjs-editor-plugin

For the brat editor, this continues to be difficult to implement because we do neither have a built-in "speaker" layer nor does this easily fit into the rendering mechanism that the brat editor uses.
