### ISSUE TITLE
What's the sense of Orthography Correction Layer?

### ISSUE THREAD

**Issue by WilliamQue** [inception-project/inception#2867]
What's the sense of Orthography Correction Layer?

Literally, Orthography Correction Layer is used to annotate incorrect words, caused by mis-spelling, mistakes during ASR(speech recoginazation).
For example: the orginal document is
```
A B C D E F G
```
But, the real is 
```
A B X Y D E F G
```
Perhaps Inception just annotating 'C' should to be replaced with 'X Y', but won't make any changes to original document.

So if tokenization, named entity recognization are based on original document with mistakes, not the corrected one, what's the sense of the correction layer?

**Comment by reckart** [comment]
For some annotation tasks it does not matter much. For example when your task is mainly to annotate named entities and occasionally you find a data/spelling problem in the text, you might care to annotate it as well so that when you eventually train your model on the annotated data, you can train your model on the corrected text where a correction exists. It is up to you to perform the necessary post-processing through.

If you have text where spelling issues are common, you might care to have a separate initial data cleaning round where you just fix the texts - however, you might want to do that not in INCEpTION but rather in a text editor with a good spelling correction.

Also, some people actually do annotate misspellings just like others annotate named entities ;)
