### ISSUE TITLE
Footer-Line is freezed and tool-tips are not shown

### ISSUE THREAD

**Issue by paaschco** [inception-project/inception#2884]
Hello, 
we use INCEpTION in an interdicplinary project and therefore work with a rather long list of document metadata. In the annotation mode, the display of these features extends beyond the footer line (with is freezed and is not moving down if the annotators scrolls down the list of document metadata features, see Screenshot 1). This affects readability. Also, we noticed that the tool tips of these features are not displayed if the footer is not visible in the browser window at the same time, see Screenshot 3 in comparison to 2. (The workaround here is to zoom out in the browser settings but there might be a better solution.) 

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1366" alt="INCEpTION_BugReport_1" src="https://user-images.githubusercontent.com/29175558/157405355-fe01cf65-ae42-468e-85e1-a18812014394.png">
<img width="1368" alt="INCEpTION_BugReport_2" src="https://user-images.githubusercontent.com/29175558/157405375-34867930-c1e3-4f4e-aa85-07e6892f7b19.png">
<img width="1354" alt="INCEpTION_BugReport_3" src="https://user-images.githubusercontent.com/29175558/157405385-0fe0777b-3376-48e9-8caf-0e71782a1c06.png">

**Please complete the following information:**
 - Version and build ID: 22.2
 - OS: the issue occurred working on both Windows and OS X
 - Browser: we tried different browsers, Safari, Firefox and Google Chrome

**Additional context**

**Comment by reckart** [comment]
It's a bug in the CSS. Thanks for the pointer!

**Comment by reckart** [comment]
What actually should happen when there are many document metadata annotations is that a scrollbar should appear in the left sidebar.

**Comment by paaschco** [comment]
Thank you for looking at that so quick!

**Comment by paaschco** [comment]
It now works perfectly :)

**Comment by reckart** [comment]
I didn't even release yet - did you bid from the sources?

**Comment by paaschco** [comment]
No, I did not. I do not know what it was, but yesterday it seemed to me that the error was fixed. However, now I see that it is not. Very sorry for the confusion!

**Comment by reckart** [comment]
NP ;) I'll run a bugfix release over the weekend for you. Please watch GitHub and/or our mailing list to get the announcement.

**Comment by paaschco** [comment]
Thank you so much! I will do so. And just to be sure (because I am a complete newbie to this developer world...: What do I have to do as soon as the release is out?

**Comment by reckart** [comment]
Well, that depends ;) If you run INCEpTION on your own computer, then you download the new version and simply run it instead of the version you run right now. 

But I have the impression you might be using an INCEpTION running on a server somewhere outside your control? In that case, you might tell the guys that run the server that they should upgrade.

**Comment by paaschco** [comment]
Yes, you are right! I will let them know then - thank you so much!

**Comment by paaschco** [comment]
Just to let you know: Upgrading went very smoothly and now the bug is really fixed ;) Thank you so much for your work.

**Comment by reckart** [comment]
Excellent! Thanks for the feedback!

**Comment by paaschco** [comment]
If I may, I would like to ask you a quick, unrelated question: Is it possible to allow to copy text passages from a document that is being annotated? Since we use INCEpTION in an interdisciplinary project (combing annotation and content analysis) we have several open string variables or features and copy & paste would be a time saver here....

**Comment by reckart** [comment]
Tricky because marking text means to create an annotation. Actually, you can click-and-mark text (do not release the mouse button!) and then press CTRL-C to copy the marked text - but the problem is: it won't contain any spaces!

What should work but is a bit annoying is this:
* create a span layer that allows annotating across sentences
* create an annotation of that layer on the text you want to copy
* in the right sidebar, there is a "text" field which then shows the annotated text including spaces - you can copy the text from there
* delete the annotation again

**Comment by paaschco** [comment]
Thank you so much, we will try that out :)
