### ISSUE TITLE
Simplify search for boolean values

### ISSUE THREAD

**Issue by OleMussmann** [inception-project/inception#2972]
Searching for boolean values works, but is a bit complicated. You seem to need to prepend the `bool_var` value with an **escaped** plus or minus sign. ("false" values can omit the backslash, "true" values can not.)

```
<LayerX.bool_var="\-bool_var"/>
<LayerX.bool_var="-bool_var"/>
<LayerX.bool_var="\+bool_var"/>
```

Using boolean values (0/1 or true/false) would make this more intuitive.

```
<LayerX.bool_var="false"/>
<LayerX.bool_var="true"/>
<LayerX.bool_var="0"/>
<LayerX.bool_var="1"/>
```

Is that related to the Inception implementation or an upstream issue? If the latter, I'd be happy to open an issue there.

**Comment by reckart** [comment]
Thanks for the suggestion. This is an INCEpTION issue. In the class `de.tudarmstadt.ukp.inception.search.PrimitiveUimaIndexingSupport`, we simply take the label value that is calculated from a feature value and stuff that into the index. Since the label for a boolean value is rendered as `+/-value` in the annotation editor, that is also what you get in the index. It should be easy to change that.
