### ISSUE TITLE
Agreement export does not show up for Krippendorf's Alpha

### ISSUE THREAD

**Issue by GiantEnemyCrab** [inception-project/inception#2996]
**Describe the bug**
Within Agreement page, there are options, like Cohen's Kappa, Fleiss' Kappa, Krippendorf's Alpha (unitizing / character offsets), and Krippendorf's Kappa (coding / nominal).

Somehow, after calculating Krippendorf's Alpha, "export all" button does not show up, though others do show.

**Expected behavior**
In Krippendorf's Alpha, "export all" should show up.

**Screenshots**
![Screenshot from 2022-04-20 23:45:40](https://user-images.githubusercontent.com/1326079/164368120-8e32058a-afb6-4101-8a40-cfd54a96b67b.png)

![Screenshot from 2022-04-20 23:46:46](https://user-images.githubusercontent.com/1326079/164368264-726b822a-bba2-4148-bb59-54050bedb958.png)

**Comment by reckart** [comment]
Unitizing Krippendorf's Alpha does not rely on the same pre-processing as the other agreement measures. It does not require the pre-calculation of "positions" that are then compared. As a result, it can also deal with partially overlapping annotations and their agreement. For the other measures, the "export" button does allow access to the result of the pre-processing step. Since it is not used by Unitizing Krippendorf's Alpha, there is no export button.

**Comment by reckart** [comment]
What kind of export/report would you expect for a measure like the Unitizing Krippendorf's Alpha?

**Comment by GiantEnemyCrab** [comment]
This was a question from my teammate that I relayed the message here, but I don't have a respond to your question,
I think the fact that export button wasn't shown made it seem like a bug because other metrics do show the button.

**Comment by reckart** [comment]
Thanks for the feedback. In that case, I think we can close the issue.

**Comment by reckart** [comment]
If any suggestions come up for an export for this type of agreement measure - feel free to comment.
