### ISSUE TITLE
AL sidebar updates even a user has not set the value in the right sidebar.

### ISSUE THREAD

**Issue by matchlesswei** [inception-project/inception#321]
If a user makes an annotation about a token in the right sidebar. If this token is shown in the AL sidebar, AL sidebar updates and gives the next recommendation.

The refactor in #316 causes that AL sidebar updates when a user has selected the token, but hasn't made any annotation in the right sidebar for it.

@reckart wrote in #316:

> It is overkill to generate one AjaxAfterAnnotationUpdateEvent per feature and that would be necessary in order to retain the getValue(). Also, having the feature value would not be enough - we would also need to know to which feature the value actually belongs.
> 
> This is related to the kinds of refactoring we need to do for #149 or #271. Could you please open a new issue describing the problem introduced by not having getValue() anymore and fix it along with introducing the feature dropdown etc. in the AL sidebar?
> 
> Instead of getting the value from the event, I would suggest to get the value for the specific feature to which the recommendation belongs from the feature states.

**Comment by reckart** [comment]
If the user is filling in a feature in the right sidebar and this causes the AL to move to another annotation, it could be disrupting the user's flow. 

Imagine the annotation has two features A and B. A is covered by a recommender which is running in the AL sidebar, but B is not. Let's say the AL mode takes the user to some annotation X. The user is not accepting or rejecting the annotation, but instead creates a new annotation at the same location manually. Then the user fills in the feature A in the right sidebar. Next he wants to fill in feature B, but he cannot do it because after filling in feature A, the AL mode already takes him to another annotation Y. WDYT?

**Comment by matchlesswei** [comment]
Yes. 
If we record the action of annotating A and update automatically, a user can click the learning history item and go to annotation X to fill in feature B. 
If we do not update automatically, a user needs to click accept or reject (or another "move to next button") again in the AL sidebar to get the next recommendation. It is inconvenient in some layers which only have one feature (like POS).
Are there other solutions?

**Comment by reckart** [comment]
Even in layers with a single feature, I imagine an auto-advance to be quite inconvenient. Imagine the user selects a tag, but it was wrong and the user wants to correct it - that is difficult if the system has already moved the user to the next annotation, right?

It might be an option to just refresh the suggestion in the AL sidebar, but **not** to jump to that annotation in the main screen. Instead, the user would have to click on the text of the annotation in the AL sidebar in order to jump to it.

**Comment by reckart** [comment]
A dialogue box would be terrible. A checkbox whether or not to auto-advance might be an option.

I think auto-advancing after accepting/rejecting in the sidebar as well as in the main screen is desirable. 

But not when the user manually creates an annotation in the main screen he kind-of leaving the AL guidance (at least temporarily), then it should not auto-advance.

**Comment by matchlesswei** [comment]
Do you mean a checkbox for choosing whether to auto-advance or not if a user manually creates an annotation in the main screen?

**Comment by reckart** [comment]
Yes. But honestly, I wouldn't suggest to implement such a checkbox immediately. Rather have the behavior non-advancing when annotations are created through the main screen and see if some user misses the auto-advance.

**Comment by matchlesswei** [comment]
Yes, it's a good idea. I'll disable the auto-advancing.
