### ISSUE TITLE
Export of (especially large) projects fails

### ISSUE THREAD

**Issue by PavelHlubik** [inception-project/inception#3227]
### Describe the bug

When we attempt to export projects from our Inception instance to be able to further utilise annotated data, this export often fails. Small projects are usually exported with no problems, but for large projects (~900 documents) it fails almost always. This appears when exporting projects using a python script to send requests and/or using Swagger. In both cases the response is `502 Server Error`.

When we try to export the large projects manually via Settings -> Export -> Export the whole project the success rate is much higher. Even in this case a failure can happen, but much less often. 

Logs from our Inception instance do not provide a lot of insight into this problem, usually se can only find a Broken Pipe error in the log. Upon request we can provide the full log file. 

### To Reproduce

1. Go to swagger api
2. Go to `/api/aero/v1/projects/{project_id}/export.zip`
3. Fill in ID of a large project and `json` output format
4. Send request. 

### Expected behavior

To receive exported project in a `zip` file without internal server errors.

### Environment

Version and build ID: 21.2 (2021-11-30 18:31:29, build 4b4d217e)
Operating system: inceptionproject/inception:21.2 running in a docker container
Database: docker.io/bitnami/mariadb:10.5.10-debian-10-r18
Browser: not applicable

**Comment by reckart** [comment]
Can you please test if the problem persists with INCEpTION 23.9?

**Comment by reckart** [comment]
Also, when you start up INCEpTION, how much application memory does INCEpTION report to be available?

**Comment by PavelHlubik** [comment]
We run Inception with the `-Xmx4g` parameter and the pod is limited to 5Gi. Testing the new version would be non-trivial for us I am afraid.

**Comment by reckart** [comment]
When you export via the remote API, you have a **very** long running request. For the client or for proxies en-route to the server, it may seem as if the server does not respond because it takes so long to prepare the export ZIP. Maybe your client or your network infrastructure between the client and INCEpTION run into a timeout?

When exporting via the projects settings, there is no long-running request. The client triggers the export, then it monitors the export and when the export is ready, it downloads the ZIP. It should not run into timeouts. I would expect failures to export via the project settings to have other causes.

**Comment by reckart** [comment]
I had no trouble exporting via Swagger in my dev setup using the JSON format on a large project that resulted in a +400MB ZIP using 24.0-SNAPSHOT.

**Comment by reckart** [comment]
Another report about issues with failing exports: #3128

**Comment by PavelHlubik** [comment]
Thank you for your very fast reactions! We tried raising memory limits, but with no effect. Currently we are working on increasing timeout limits on our network infrastructure, as it really seems this might be the issue. We will first try to change settings of our k8s ingress.
