### ISSUE TITLE
Assigning a document to an annotator in dynamic mode

### ISSUE THREAD

**Issue by LeaKawa** [inception-project/inception#3441]
### Describe the bug

There is a graphics bug when manually assigning a document to a specific annotator in dynamic mode. After selecting a document, the window shifts its position and the 'confirm' button disappears (see screenshot). The user has to click somewhere outside the window and re-open it, after which they see the expected selected document and confirm button. 

### To Reproduce

1. Go to 'Annotators' in the dynamic workload overview table
2. Click on 'Select an annotator' and select an annotator
3. Click on 'Assign document' and select a document

### Screenshots

![Inception-2](https://user-images.githubusercontent.com/115624978/195307675-4e47f710-345a-4830-b09e-d604921f92d4.png)

### Environment

Version and build ID: 25.0 (2022-10-10 19:02:52, build 7c03e11c)
Operating system: MacOS Monterey
Browser: Safari

**Comment by reckart** [comment]
Tentatively scheduling for 25.2...

**Comment by reckart** [comment]
The problem here is that the dropdown from the multi-select input does not open itself within the "Annotators" dropdown, but rather directly at the page-level just below the footer element. This causes the `sticky-dropdown` magic that is applied to the "Annotators" dropdown no to take effect.

The best solution would probably be to use a modal dialog instead of a dropdown here. That would also provide more space and it may be possible to re-use the document selection table from the open documents dialog... it could also be tried to re-used that within the dropdown, but I don't think it would work well

But this is something that won't fit into a bugfix release. Moving to next feature release.

**Comment by LeaKawa** [comment]
Thanks for the update!
