### ISSUE TITLE
Tagset wasn't created when tagged files were uploaded

### ISSUE THREAD

**Issue by yanirmr** [inception-project/inception#3486]
### Describe the bug

Whenever I upload an annotated file with custom layers into a new project, the layers appear but not the tagset. Due to this, I cannot continue to tag that file until I create the tagsets from scratch and connect them to the appropriate layers.

### To Reproduce

1. Create a new project.
2. Upload typesystem
3. Upload xmi file
4. Get into the project layers and see the custom layers.
5. Get into the custom layers and look for their tagset -> empy.

### Expected behavior

One or both of the following were expected:
1. Systemfile will be used to upload tagsets
2. Based on the tags in the file, a tagset will be generated. 

### Environment

Version and build ID: 25.1 (2022-10-11 21:15:38, build e85988ac)
Operating system: Linux
Browser: e.g. Chrome

### Additional context

Several issues occurred when I tried to recreate a project from exported files.

**Comment by reckart** [comment]
Tagsets are optional. You can work with your data even if you disconnect/remove tagsets from the layers - only you won't get dropdowns or auto-completes because INCEpTION no longer knows your tagset.

While basic tagset information is included when exporting annotated data as XMI, this is just indicative information to make it easier for downstream applications. INCEpTION does not use this information at all. You can export tagsets separately if you wish from the tagset panel in the project settings. Otherwise they are included in full project exports.

**Comment by yanirmr** [comment]
I appreciate your prompt response.

What is the most convenient way to save this setting for future use? Backups and other emergency situations?

**Comment by yanirmr** [comment]
I read your response in the other thread...

**Comment by reckart** [comment]
Best export the entire project from the "Export" panel in the project settings. The full project export includes all data and can be conveniently re-imported into the same or a different instance. Alternatively, export the fully project export via the remote API. Also consider performing regular backups of the database and application home folder. Remember to always test if restoring a backup works.
