### ISSUE TITLE
Order of matches found in knowledge base search is not correct

### ISSUE THREAD

**Issue by ahoo1260** [inception-project/inception#3822]
**Describe the bug**
Our knowledge base has different string properties ( for example prefLabel, altLabel, label ). We like to get the entity with closest match in all of these properties, for example, if I search for "hand", the entity with _altlabel_ "hand" should be shown on top of list. 

**To Reproduce**
I have attached the project and the knowledge base.
import knowledge base local with IRI Schema
After importing knowledge base is done, search "hand"

**Expected behavior**
it should show "Hand structure (body structure)" on top of the results for search.

same as search results as Snomed browser https://browser.ihtsdotools.org/?perspective=full&conceptId1=85562004&edition=MAIN/2023-01-31&release=&languages=en&latestRedirect=false

**Screenshots**

![image](https://user-images.githubusercontent.com/26032359/220131441-dc067027-60a6-4e3d-96db-7bb6b4f0ed05.png)

But we expect this order:

![image](https://user-images.githubusercontent.com/26032359/220133896-4006ddfc-9a98-444f-871d-45d0ee803d64.png)

**Please complete the following information:**
- Version and build ID: 26.8
- OS: Linux (ubuntu 20.04)
- Browser: chrome

**Additional context**
The project and kb file is attached

[hand_project16118132736551889752.zip](https://github.com/inception-project/inception/files/10785260/hand_project16118132736551889752.zip)

[vomiting_hand_graph.ttl.zip](https://github.com/inception-project/inception/files/10785253/vomiting_hand_graph.ttl.zip)

**Comment by reckart** [comment]
@ahoo Thanks for the report - very insightful! I can reproduce the issue and am looking into a fix.

**Comment by ahoo1260** [comment]
Thanks. Preferred label is also ok! However, our annotators can be more confident if they see the exact match on the top of list ( which is hand ).

**Comment by reckart** [comment]
Would you then expect to see **only** `Hand` and not have `Hand structure (body structure)` in the list at all?

The label rendered on top of the text in the annotation bubble will always be the preferred label. I believe it would confuse the annotators if the item they chose is not the item that will be rendered in the text then.

I guess the best way would be to display in the item both, the preferred label and the label that had the best match....?Unfortunately also the more complicated solution to implement ;)

**Comment by ahoo1260** [comment]
Is it possible to see both?  it is now the preferred name and the link to Snomed. If there is no room for everything to be shown, I believe the link can be replaced by the label that had the best match...

**Comment by reckart** [comment]
IMHO the IRI should also remain visible because some people enter the IRI directly and they should be able to compare what they entered to the items in the dropdown.

**Comment by ahoo1260** [comment]
very valid point. It is important that annotators can put the IRI

**Comment by reckart** [comment]
How about this:

<img width="561" alt="Screenshot 2023-02-21 at 20 52 11" src="https://user-images.githubusercontent.com/1410238/220444634-33c9142f-6993-4670-a7dc-39f732d3028f.png">

**Comment by ahoo1260** [comment]
yes, looks exactly like what we want! Is there a reason than "hand bath" is the second match? and not "handicap"? I am trying to understand the sorting algorithm. Thank you

**Comment by reckart** [comment]
Ok, there is a longer story here :)

First, I had to change the settings in the project that you provided a bit - it was missing the settings to take the alternative labels into account:

<img width="1045" alt="Screenshot 2023-02-21 at 21 07 18" src="https://user-images.githubusercontent.com/1410238/220447422-1498c786-d4fd-4dc8-bd55-0648e1a0ef82.png">

In the screenshot above, I only had added `http://www.w3.org/2004/02/skos/core#altLabel` yet. Then I checked the `Handicap` entry in the KB and it turns out that it does not have a `http://www.w3.org/2004/02/skos/core#altLabel`, only a `http://www.w3.org/2004/02/skos/core#prefLabel` and a `http://www.w3.org/2000/01/rdf-schema#label` - so I added the `...prefLabel` as well. With both the `...altLabel` and the `...prefLabel as additional matching properties, we get:

<img width="529" alt="Screenshot 2023-02-21 at 21 09 40" src="https://user-images.githubusercontent.com/1410238/220447802-a49214d9-3488-49a2-9d24-17ef286be2a2.png">

In the gray debug info, you can see that `Hand gun`, `Hand saw` and `Handicap` all have the same edit distance to the query (`levQuery=5  levQueryNC=4`) - at which point the ordering falls back to alphabetic ordering and then ` ` comes before `i`.

**Comment by ahoo1260** [comment]
Thank you for explanation. It makes sense. I am very happy with the output

**Comment by reckart** [comment]
You can try this out in INCEpTION 27.0-beta-4: https://inception-project.github.io/downloads-beta/

**Comment by ahoo1260** [comment]
thank you Richard, I tested it and it works as expected. Will you make a release in the coming days?

**Comment by reckart** [comment]
I hope 27.0 can be released within the next 14 days - but I never give guarantees :) If for some reason it should get delayed, a 26.9 release can be added in between and that would also include the fix.

**Comment by reckart** [comment]
There will not be a version 26.9. 

A release candidate 27.0-rc-1 is now available and you may consider testing it: https://github.com/inception-project/inception/releases/tag/inception-27.0-rc-1

**Comment by reckart** [comment]
https://hub.docker.com/layers/inceptionproject/inception-snapshots/27.0-rc-1/images/sha256-81e705712099c32ea6d501730c5ed8dee5ca2fa096f4dd4ef82ea0f25ead5615?context=explore

**Comment by reckart** [comment]
For future reference - when configuring INCEpTION for Snomed, the following settings should be made:

* IRI Schema: OWL
* Root concepts: `http://snomed.info/id/138875005`
* Additional matching properties: `http://www.w3.org/2004/02/skos/core#altLabel`, `http://www.w3.org/2004/02/skos/core#prefLabel`
