### ISSUE TITLE
Cross-sentence tagging

### ISSUE THREAD

**Issue by 2xXLunAXx2** [inception-project/inception#3883]
**Describe the bug**
When I tag cross-sentence tagging (e.g., one tag for sentences 45-49) there are two things that might happen:
1. All sentences move to the line of the first tagged sentence (see example 1 below). 
2. The sentences stay in their respective lines (see example 2 below).

**To Reproduce**
I'm not sure how to reproduce it. I'm not sure when the sentences move and when they stay in their lines. I think it might be that some layers do (1) and other layers do (2).

**Expected behavior**
Either all sentences stay in their respective lines, or all of them move to one line.

**Screenshots**
![2023-03-16 at 11 19 10](https://user-images.githubusercontent.com/110154717/225589430-14244c86-c12c-4ed1-8575-42b86d850ec7.jpg)
![Screenshot 2023-03-16 142239](https://user-images.githubusercontent.com/110154717/225616014-e7b481f4-6c6f-4aba-8d69-cecae642ca22.png)

**Please complete the following information:**
 - Version and build ID: 26.6 build d6ce2c72
 - OS: Windows
 - Browser: chrome

**Additional context**
We look for a way to analyse cross-sentence taggings (see the thread here- https://github.com/catalpa-cl/inceptalytics/issues/21). Maybe this change in the representation of these tags mean that some of them can be analyzed? 

Thank you!

**Comment by reckart** [comment]
Can you export that toy project so I can have a look at it?

The brat visualizer cannot wrap words inside a row if they have a covering annotation. This should be only a visualization issue and have nothing to do with the internal representation. 

I do not understand how this relates to the inceptalytics issue. I would say that if you want to analyze cross-sentence annotations, then you need to make sure that you directly iterate over these annotations instead of iterating over the sentences and then looking only at the annotations covered by the sentence.

**Comment by 2xXLunAXx2** [comment]
Thank you, 
Is there a way to export only few sentences from the project so i won't have to export the whole file?
Anyway, it's good to know that the representation stays the same in both cases so there won't be any future issues. 
Regarding the visualization- note that this is the same case (cross-sentence annotation) in both screenshots. i.e., it should look the same. Wonder what happened... in any case, it's not really critical for our project so it's fine.
