### ISSUE TITLE
PDF highlighting disables after double-clicking on a recommended annotation

### ISSUE THREAD

**Issue by amckenny** [inception-project/inception#4008]
### Describe the bug

When using a recommender in PDF annotation, I get the gray highlights and bubbles. Double-clicking on the gray bubble *does* remove the recomendation as expected; however, after double-clicking on one of the gray bubbles to remove that recommendation, I am not able to click-drag to annotate anything anymore. 

To restore this ability, I need to hover my mouse over one of the other gray boxes (clicking is not necessary). At that point, the ability to click-and-drag for annotation is restored until the next time that I double-click a recommendation to remove it.

### To Reproduce

1. Go to a PDF with recommender 'on'
2. Double-click on the gray bubble above one of the recommendations
3. Observe that the recommendation goes away
4. Attempt to click-and-drag over unannotated text
5. Observe nothing is highlighted
6. Hover over a recommendation bubble
7. Attempt to click-and-drag over unannotated text
8. Observe that selection is highlighted

### Expected behavior

1. Go to a PDF with recommender 'on'
2. Double-click on the gray bubble above one of the recommendations
3. Observe that the recommendation goes away
4. Attempt to click-and-drag over unannotated text
5. Observe that selection is highlighted

### Screenshots

[screencapture video of bug](https://www.dropbox.com/s/g5dydrrdz1jp6yo/PDF%20recommender%20issue.mp4?dl=0)

### Environment

INCEpTION version: 27.0 (2023-03-07 13:00:34, build c9bb50a0)

Docker info:
    - App Version: inceptionproject/inception:27.0
    - DB Version: mariadb:10.7
    - (Created using your suggested code from the docker compose code from your website, but changed the app version to 'latest')

Browser info:
    - Google Chrome Version 113.0.5672.127 (Official Build) (64-bit)

**Comment by reckart** [comment]
Thanks for the issue report and the explanatory video! Looks like the internal state of the PDF editor gets a bit messed up on a reject. I'll have a look.

The message about **Relations cannot be created from/to synthetic annotations** comes up because you all so slightly move the mouse between pressing and releasing the mouse button - and then the editor recognizes it as a drag action - and drag actions to create relations are not possible on suggestions (as the message says). It would probably be a good idea to look into that as well and make it a bit less sensitive.

**Comment by amckenny** [comment]
Great - thanks for your help Richard!
