### ISSUE TITLE
Efficient Data Migration for INCEpTION Tool Across AWS EC2 Instances

### ISSUE THREAD

**Issue by shgulomov** [inception-project/inception#4211]
**Is your feature request related to a problem? Please describe.**
I am experiencing difficulty in exporting data from the INCEpTION tool running in Docker on an EC2 instance in AWS to another instance. The issue arises due to mismatch data on the current instance and new instance.

**Describe the solution you'd like**
I would like a solution that allows me to export the INCEpTION tool data from the current EC2 instance to a new, high-performance instance. I have tried taking a snapshot of the EC2 volume, creating a new volume, and attaching it to the new instance. However, when I mount the volume and run the INCEpTION tool, the data does not match the data from the old EC2 instance. Surprisingly, the new instance UI shows projects of INCEpTION tool running in Kubernetes without actual data ( K8s pod, EC2 and new EC2 instances have connected to the same MariaDB database in AWS).

**Describe alternatives you've considered**
An alternative solution could be to find a way to ensure that the data from the old EC2 instance is accurately transferred to the new instance when using the snapshot and volume creation method.

**Additional context**
I need assistance in finding a solution that allows me to successfully export the INCEpTION tool data from the current EC2 instance to a new, high-performance instance while preserving the integrity of the data.

**Comment by reckart** [comment]
The most efficient way of migrating INCEpTION from one machine to another should usually be:

- create a dump of the SQL database on the source machine, copy it to the target machine, and there import it again into the target SQL DB
- rsync the data folder from the source machine to the target machine
- ensure that the location of the data on the target machine and the credentials for the SQL db on the target machine are the same as on the source machine, otherwise update e.g. your `settings.properties` accordingly
- if your are using system.d, register INCEpTION with it on the target machine as described in the documentation
- start up INCEpTION
