### ISSUE TITLE
Can we just need to create a scheme for inplementing the Leipzig Glossing Rules?

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception#4271]
I'm attending a course of Syntax Linguistics. The teacher asked us to submit a homework based on[ Leipzig Glossing Rules](https://www.eva.mpg.de/lingua/pdf/Glossing-Rules.pdf). So I have an idea, is it possible to make it with the great INCEpTION?

**Comment by reckart** [comment]
This is of course not a homework-making forum :) 
You could maybe have a look at the existing layers "Lemma", "Morphological analysis", and "Text normalization" to get some inspiration - or define your own set of custom layers with appropriate names and features for the LGR.

**Comment by fishfree** [comment]
@reckart Thank you very much for your tip. Would you pls share more detailed or a built-in whole constraints set file? I found nohwere to export a constraints set file, either in the repo codes.

**Comment by reckart** [comment]
Constraints files used for automated testing can be found here:

https://github.com/inception-project/inception/tree/main/inception/inception-constraints/src/test/resources/rules

Otherwise, examples can be found in the [documentation](https://inception-project.github.io/releases/29.8/docs/user-guide.html#sect_constraints).

**Comment by reckart** [comment]
Also the frame annotation example project contains constraints. You can find it [here](https://inception-project.github.io/example-projects/frame-annotation/).

**Comment by fishfree** [comment]
Thank you very much for your explanation!
