### ISSUE TITLE
Display suggestions for the identifier feature of Named Entity annotations

### ISSUE THREAD

**Issue by rcffc** [inception-project/inception#45]
Generate IRI suggestions for annotations and recommendations on the Named Entity layer and display them as suggestions.

**Comment by reckart** [comment]
It looks like you were looking into refactoring the entire classifiers API. That is not necessary. We only need to allow classifiers to contribute settings and a UI for these settings. Let me quickly run you through how did that for the AnnotationFeatures:

* In the `FeatureSupport` interface, I have added three new methods: `createTraitsEditor`, `readTraits` and `writeTraits`. The `createTraitsEditor` by default returns an empty panel. The other methods also do nothing by default.
* when the use selects a specific feature type in the feature detail editor, the UI asks the `FeatureSupport` responsible for the feature type about a traits editor (`createTraitsEditor`).
* presently `ConceptFeatureSupport` returns a traits editor and also the `PrimitiveUimaFeatureSupport` for String features.
* the traits editor gets embedded as a sub-form into the `ProjectLayersPanel.FeatureDetailForm` and it gets submitted along with the user pressing the "save" button on the main form. 
*the sub-form in the `ConceptFeatureTraitsEditor` implements `onSubmit` and there it saves its data to the `AnnotationFeature` model from the main form using the `ConceptFeatureSupport.writeTraits` method.
* in the main form `ProjectLayersPanel.FeatureDetailForm`, the saving of the `AnnotationFeature` is not made in the `onSubmit`method, but rather in the `onAfterSubmit` method, so it is guaranteed that the sub-form has already written the traits to the `AnnotationFeature` before that is saved.

The case of the recommenders is very similar.

Instead of the `FeatureSupport` interface, we have to add the three new methods `createTraitsEditor`, `readTraits` and `writeTraits` to the `ClassificationToolFactory`. The traits editor gets embedded not into `ProjectLayersPanel.FeatureDetailForm` but rather into `RecommenderEditorPanel`.

For those classification tools where we want to add new settings, we then have to implement the three methods mentioned above. For classification tools where we do not want to support any additional settings, we just don't. Each classification tool will have its own traits class. E.g. we might have `OpenNlpNerClassificationToolTraits` which offers a setting for the feature frequency cutoff during training and a `OpenNlpNerClassificationToolTraitsEditor` which provides the UI to modify this setting.

**Comment by rcffc** [comment]
Yes, thanks.

**Comment by rcffc** [comment]
![screenshot from 2018-04-20 16-51-18](https://user-images.githubusercontent.com/13070150/39058371-eba6b938-44bb-11e8-8632-f6ff2a3ab446.png)

**Comment by rcffc** [comment]
I had to disable filtering the rendered predictions for existing annotations and overlapping predictions, because right now we can only specify a layer not a feature: 
1. vdoc.spans(layer.getId()) - RecommendationSpanRenderer 
2. CasUtil.selectCovered(aJcas.getCas(), type, aWindowBegin, aWindowEnd) - Predictions

**Comment by reckart** [comment]
@rcffc what needs to be done to re-enable the functionality?

**Comment by rcffc** [comment]
It should be possible to get existing annotations of a specific feature instead of the whole layer.

**Comment by reckart** [comment]
> It should be possible to get existing annotations of a specific feature instead of the whole layer.

You mean recommendations?

**Comment by rcffc** [comment]
No, the existing annotations, so we can remove predictions overlapping them.

**Comment by reckart** [comment]
You'd have to iterate over all annotations in the relevant layer and search for those having a specific feature value/non-null value.

**Comment by reckart** [comment]
```
TypeAdapter adapter = annotationService.getAdapter(layer);
Type type = getType(aJcas.getCas(), typeAdapter.getAnnotationTypeName());
AnnotationFeature annotationFeature = annotationService.getFeature(featureName, layer);
FeatureSupport featureSupport = featureSupportRegistry.getFeatureSupport(annotationFeature);
Feature labelFeature = type.getFeatureByBaseName(featureName);

Collection<AnnotationFS> annotations = CasUtil.select(aJcas.getCas(), type);
for (AnnotationFS fs : annotations) {
  String value = fs.getFeatureValueAsString(aLabelFeature);
}
```

**Comment by rcffc** [comment]
I am having a bit of a trouble working out how to update an existing annotation in RecommendationEditorExtension.actionAcceptRecommendation(). Consider the case when we have a prediction for "Obama" annotated with "PER" on the "value" feature and a **prediction** "https://www.wikidata.org/entity/Q76" on the "identifier" feature. 

We would need to select the annotation at this token on the NamedEntity layer which already holds a prediction.How do we retrieve the existing span and edit it? We don't want to add a new span.

**Comment by reckart** [comment]
@rcffc you can use `WebAnnoCasUtil.selectAt` to get all annotations of the current layer type (which you get from the layer adapter) at the position where you would create the annotation. If selectAt() returns annotations, then I'd pick the first one of them and that would be the annotation where you set the feature.
