### ISSUE TITLE
BioC exported from INCEpTION cannot be imported again due to missing mandatory metadata

### ISSUE THREAD

**Issue by azankl** [inception-project/inception#4533]
When trying to upload a file in Bioc-XML format to Inception, I get a 'source file does not exist' error, see screenshot below:

<img width="1512" alt="Screenshot 2024-02-21 at 11 02 55 am" src="https://github.com/inception-project/inception/assets/4812335/ec10ad91-42e2-4aeb-9736-189d8641bae0">

From the error message, it seems that Inception is looking for the file in /srv/inception/... while I selected the file from my desktop.
This only happens with BioC-XML files, importing a plain text file from my desktop to Inception works as expected.

**Please complete the following information:**
 - Version and build ID: - INCEpTION -- 31.0 (2024-02-06 23:22:40, build 8e5dd706)
 - OS: OSX 14.3.1 (Client), Inception running on remote Red Hat server
 - Browser: Safari 17.3.1

**Comment by reckart** [comment]
Thanks for the report. You are probably trying to re-import a BioC file exported from INCEpTION back into it. The exporter currently has a bug that the `key` and `date` BioC metadata items are not written to the exported file. 

**Workaround:** Until this bug is fixed, you can manually add these elements to your BioC file at the beginning of file. Make sure that both elements actually contains something - they must not be empty:

```
<collection>
    <key>foo</key>
    <date>2020-10-02</date>
    <source>file:/...</source>
    <document>
...
```
