### ISSUE TITLE
Ability to define the role of a link without having to use the set button

### ISSUE THREAD

**Issue by bgittel** [inception-project/inception#4744]
all my annotators complain about a small issue: I have a layer with a link feature. In order to annotate it, one has 1) to select the kind of link feature in the annotation or curation mode and 2) one has to click "Set". The second step is superfluous and leads to a lot of easy mistakes in practice (because if you forget it, you will annotate not the link feature but a new autonomous span)

**Comment by reckart** [comment]
I'm not sure I can reproduce that description.

https://github.com/inception-project/inception/assets/1410238/f3f680ad-2ac2-4b31-8985-4012ccad2dd2

In order to annotate, one has to

* enter (or select) the role for the link
* click *add* to add the empty slot with the given role
* select and existing annotation or mark a span of text to fill the slot

The **set** button is not actually involved at all. The **set** button is only use to change the role of an already existing slot.

https://github.com/inception-project/inception/assets/1410238/64763821-f3ba-4313-88e9-3a0b498316d8

**Comment by reckart** [comment]
@bgittel ping?

**Comment by bgittel** [comment]
Sorry for the late response (holidays), the issue seems to be gone in 33.3, i remember for sure that i had to select the role, than "add" and than "set" to be able to fill the slot. Thanks
