### ISSUE TITLE
Connecting annotation and entity with arc over different pages

### ISSUE THREAD

**Issue by s2fische** [inception-project/inception#4809]
**Describe the bug**
When marking a Bezugsentität (both Wertender/gewertete Entität), if the entity is on a different page than the Wertung itself, the arc that visually connects the two annotations doesn't show up, although the connection has been successfully made, as can be seen in the menu on the right. The same problem appeared with Codierungen and Codierender/codierte Entität.

**To Reproduce**
1. If a Wertung has been set, annotate a Bezugsentität (Wertender and/or gewertete Entität) outside the span of the Wertung, at least one sentence away. The arc should be visible if they are on the same page.
2. If necessary, use Preferences to force Wertung and entity to be on different pages of the document (set it to brat sentence-oriented and reduce the amount of sentences on the page).
3. The error is that the arc, visible before, has now vanished.

**Expected behavior**
Usually, these arcs should appear so you can see the connection between Wertung and entity at first glance. 

**Screenshots**
<img width="959" alt="Screenshot 2024-05-17 163312" src="https://github.com/inception-project/inception/assets/170112224/f3f1258d-669c-4623-820b-9e9d70c316f5">
<img width="959" alt="Screenshot 2024-05-17 164230" src="https://github.com/inception-project/inception/assets/170112224/1f37e52b-0711-4905-b437-4fa95ba37a4e">
<img width="959" alt="Screenshot 2024-05-17 164337" src="https://github.com/inception-project/inception/assets/170112224/4c46301b-2379-4983-95f7-28b7181d8c9c">
<img width="959" alt="Screenshot 2024-05-17 165551" src="https://github.com/inception-project/inception/assets/170112224/f36edde1-e8fa-4021-a9c0-83a3238d01a6">
<img width="959" alt="Screenshot 2024-05-17 165619" src="https://github.com/inception-project/inception/assets/170112224/211527c7-0071-4300-be9c-48f28bc47125">
<img width="959" alt="Screenshot 2024-05-17 165659" src="https://github.com/inception-project/inception/assets/170112224/ab140286-7e6c-4007-ad1e-a04ace9e4f0d">

**Please complete the following information:**
 - Version and build ID: 31.3 (2024-03-12 20:11:22, build 6743f933)
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
Same thing happened to my colleague using Chrome (also Windows).

**To do**
* [x] Make it work for relations
* [x] Make it work for link features

**Comment by reckart** [comment]
An arc is currently only visible if both endpoints are visible. 

> The arc should be visible if they are on the same page.

If the start and end point are on the same page, the arc should be visible. I haven't noticed a case in your screenshots where this is not the case. If it is the case, could you please point out the screenshot with the respective example?

> Usually, these arcs should appear so you can see the connection between Wertung and entity at first glance.

You would only be able to see the connection between Wertung and the entity if both Werung and the entity are visible. If one is outside the currently visible viewport - even if an arc would be drawn - you wouldn't be able to see that there is a connection between the two - only that there is some connection.

I agree though that it would be useful if there was some visual representation of a partial arc even if only one of the arc endpoints is visible on screen.

**Comment by s2fische** [comment]
> If the start and end point are on the same page, the arc should be visible. I haven't noticed a case in your screenshots where this is not the case. If it is the case, could you please point out the screenshot with the respective example?

This is how it should look (arc visible even over several lines, which is why I included these):
<img width="959" alt="Screenshot 2024-05-17 164230" src="https://github.com/inception-project/inception/assets/170112224/b1ef8daa-4364-427d-a126-7993da1380d9">

This is how it looks when entity ("sie") and Wertung are separated by different pages (arc invisible):
<img width="959" alt="Screenshot 2024-05-17 164337" src="https://github.com/inception-project/inception/assets/170112224/a5bf6aaa-dece-4f28-85cb-b871bd1bef0d"><img width="959" alt="Screenshot 2024-05-17 163312" src="https://github.com/inception-project/inception/assets/170112224/48a0a852-7c2a-4e38-bb6f-b242529e2b1a">

<img width="959" alt="Screenshot 2024-05-17 164337" src="https://github.com/inception-project/inception/assets/170112224/a5bf6aaa-dece-4f28-85cb-b871bd1bef0d">

**Comment by reckart** [comment]
As I said - currently an arc can only be drawn when both endpoints are visible on the same "page". INCEpTION tells the adapted brat rendering engine that is used here to draw a connection between e.g. the span annotations on `sie` and on `ich werde nun für mein Lebtag frei bleiben`. However, if only one of the endpoints spans (e.g. the one on `sie`) is visible, INCEpTION cannot tell the rendering engine to draw an open-ended relation to beyond the end of the page - the rendering engine does currently not have such a functionality.

After you report, I have looked a bit into this any played around with ideas to start supporting such a functionality. In particular, I have tried to introduce an artificial span at the beginning/end of the page to which I could connect arcs that go beyond the page end. That idea kind of works, but it currently looks very ugly and there are a bunch of open questions regarding the implementation that I haven't resolved yet. 

In order to fix the ugly looks, I have to make further adjustments to the rendering engine that INCEpTION adapted from brat, but in areas that I am not too familiar with. So it is a bit tricky.

Right now, I can only suggest that you might try to increase the number of visible lines in the preferences dialog to maybe alleviate the issue a bit. Also, you can open the annotation sidebar on the left which gives an overview over all annotations including the potentially invisible arcs - so at least you have another way of finding them which does not require you having to select one of the endpoints.

**Comment by s2fische** [comment]
> I agree though that it would be useful if there was some visual representation of a partial arc even if only one of the arc endpoints is visible on screen.

That would be really helpful, since increasing the number of lines on one page becomes confusing very quickly, especially in curation mode.
