### ISSUE TITLE
When marking a NamedEntity mention in the text to annotate the identifier, the mention should be loaded into the AutoCompleteBoxField in the right Sidebar

### ISSUE THREAD

**Issue by rcffc** [inception-project/inception#53]
Currently the AutoCompleteBox is empty when a mention is marked. To improve UX, it should be loaded with the marked mention, as is visible in the picture.
![selection_008](https://user-images.githubusercontent.com/13070150/38767149-2919df36-3fdd-11e8-86dc-0f02fb2b3854.png)

**Comment by rcffc** [comment]
This behavior already exists for clicking on existing annoations:
![selection_009](https://user-images.githubusercontent.com/13070150/38767189-8d042e66-3fdd-11e8-9984-7ca4747efd96.png)

**Comment by reckart** [comment]
Some scenarios:

Scenario 1:
* a user marks a word to create a linking annotation
* the text of the word is pre-loaded into the auto-complete
* the user marks the next word
* -> Would the pre-loaded value have any effect?

Scenario 2:
* a user marks a word to create a linking annotation
* the user clicks into the auto-complete
* the user clicks outside of the auto-complete
* -> Would the pre-loaded value disappear now since the user has not chosen an actual suggestion to accept?

**Comment by rcffc** [comment]
As discussed today with @reckart and @Rentier, allowing the display of suggestions of a marked mention  on focus is not trivial, as it involves overwriting a JavaScript file from Kendo. Due to high effort this issue is dropped for now.

**Comment by reckart** [comment]
The marked text is automatically used when showing the linking candidates. When the user presses space in the concept feature editor, only the mentioned text is used. Copying the mention text into the linking field is therefore no longer necessary.
