### ISSUE TITLE
Improve performance of loading results from external search

### ISSUE THREAD

**Issue by az79nefy** [inception-project/inception#628]
**Is your feature request related to a problem? Please describe.**
It takes ages to load results and the data that is returned from the endpoint seems to be huge.

**Describe the solution you'd like**
- [ ] Change the query such that only relevant information is returned for the query results table: document id, document title (in our current case the URI), score, highlights
- [ ] Remove `text` field from `ExternalSearchResult`
- [ ] Introduce some class to represent a full external document, e.g. `ExternalDocument`
- [ ] for importing and displaying in the detail page, use `ExternalSearchProvider.getDocumentById()` which should return the `ExternalDocument` that contains a field with the full text

**Describe alternatives you've considered**
Load less query results (currently 1000 documents are loaded).

**Comment by reckart** [comment]
I think this needs to be addressed using asynchronicity, caching and better paging.

The reason that we are currently retrieving all the data in one go before showing it is, that we want to have access to the full texts in order to allow us to perform some kind of reranking on them. But obviously, this makes things *very* slow.

* ** Asynchronicity I + Paging** - we probably should start showing results as soon as they come in and not only after all results have been retrieved from the remote index. The first 10 results can be simple shown. Once the next 10 results come in, we'd need to add a new page. It may be possible to use Websocket (to have the server send an update to the browser) for this or maybe some other technique.
* ** Asynchronicity II + Caching** -  Also, we probably should not load the full texts as part of the query that we use to display the results, but rather as a second background process. We could cache the full texts locally, so we'd only have to load them if 1) timestamp on the remote index has changed or 2) if we didn't load them before.

**Comment by reckart** [comment]
For caching, we now have #781.

**Comment by reckart** [comment]
@az79nefy I believe that `ElasticSearchProvider.executeQuery(...)` retrieves the full document text at the moment, but we do not actually use it. Also the `ExternalSearchResult` includes the full text in the `text` field at the moment, but we do not need it there.

Instead we should be able to use the `ExternalSearchProvider.getDocumentById()` to retrieve the full text when importing a document into the project or when displaying the document in the detail page. That should save quite a bit of time/space I think.

**Comment by jcklie** [comment]
Related: #988
