### ISSUE TITLE
Add implicit learning actions to event log from AL sidebar

### ISSUE THREAD

**Issue by matchlesswei** [inception-project/inception#65]
Implicit learning actions should be added to the event log.
In the action log, we should log: the actions recorded in the sidebar history, plus other recommendations.

**Comment by matchlesswei** [comment]
@reckart @betoboullosa are the following actions implicit learning actions? Are there other implicit actions?

If the user accepts an annotation:
- Other recommendations beside the accepted one are considered as rejected

If the user does an annotation in the right sidebar:
- Other recommendations beside the annotated one are considered as rejected

**Comment by reckart** [comment]
@betoboullosa in the case where the user creates an annotation with the right sidebar, it is quite difficult to log the suggestions in the context of the new annotation because the right sidebar doesn't know about the recommendations. So in that case, I would say that we should not do anything special.

**Comment by reckart** [comment]
@matchlesswei @betoboullosa or am I mistaken? Do we log an annotation created via the main view/right sidebar as a "correction"?
