### ISSUE TITLE
Add "allowed to run" policy to scheduling

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#773]
There are critera whether a task can be run (e.g. not if a similar task is running already)

**Comment by reckart** [comment]
The ` `de.tudarmstadt.ukp.inception.scheduling.Task` has a `isReadyToStart()` method since inception-20.0 (a31d1b0510764a88c66526773a07e18316622b49) which is used e.g. in the `DebouncingTask` to indicate if timeout has passed. There is also the `MatchableTask` since inception-20.0 (d79da0642d793ae3f98de9306589ea6894fa4f27) which is used by the search system to avoid scheduling redundant indexing tasks for a given project / document.
