### ISSUE TITLE
A quick way to go to the document annotation after importing from external search

### ISSUE THREAD

**Issue by shinyichen** [inception-project/inception#792]
**The problem**
Most likely after importing documents from external search page, users will want to start annotating on these documents. However, it takes several steps to get start annotating; 1. Click on projects, 2. select the project, 3. finding the document just imported from a possibly long list, 4. click on the document, 5. click 'Open'. 

It would be nice to have a quicker way to get to a document just imported directly from the external search page, perhaps with just a single click.

**Possible solution**
Replace the "import" buttons with an "open" button if that document has been imported, which opens it up for annotation when clicked.

**Comment by reckart** [comment]
In order to be able to make use of the external search, the user must already have selected a project before opening the external search. You can jump back to that project via the "Dashboard" link in the menu bar. That at least saves steps 1-3 already.

Replacing the "import" link with an "open" link after a document has been imported sounds like a good idea though!
