### ISSUE TITLE
Annotators should be able to reopen a finished document

### ISSUE THREAD

**Issue by qiuwei** [inception-project/inception#898]
I am thinking about why the annotator is banned from reopening a document closed by him/herself.
The annotator knows better whether the document is really finished or not.

In a real project, this feature really bugs me. Quite often the annotators consider the annotation is done, but after a while, they realized they've made mistakes. However, they cannot go back and make modifications.

**Comment by GiantEnemyCrab** [comment]
I am currently in transition from WebAnno to INCEpTION, and I've been impressed by feature additions including being able apply text-based filters as well as bulk changing in Monitoring.

In my situation, the workflow is organized by ticketing system like JIRA, and each annotator gets assigned a range of files to work on, and curation readiness is indicated after multiple people completing the "annotation-phase" JIRA tickets.

This means that while the "annotation-phase" JIRA ticket is in progress, annotators can reopen the "ANNOTATION-FINISHED" documents without affecting the curation. Once annotators complete the annotation tickets, they move onto other annotation documents, so that curation work is not affected. Therefore, in a workflow like this, it is a fair deal to be able to toggle between annotation finished vs in-progress, as long as the JIRA ticket is not marked completed.

Some annotators' working hours aren't the same as others. Some might have availability on the weekend only, and it is not productive to wait until the next weekend to have the document reopened.

I've even set up some chatbot where annotators can type in some commands to reopen which file from which project, and it uses the REST API on the backend to retrieve chat messages and reopen the specified document. This was initially setup due to a very slow monitoring page from an earlier WebAnno version, but ended up allowing individuals to reopen and it has been very efficient and helped a lot.

What I am thinking of is to have a project-level checkbox option to enable toggling of annotation document locked vs unlocked. When this checkbox is on, the "lock" button can be clicked, and I think a popup screen can be shown, similar to how annotators get a confirmation window when finishing a document.

Such a project-level checkbox can be off by default, but I still think having this option can be very effective.

**Comment by reckart** [comment]
@GiantEnemyCrab thanks for the comment. With the improvements to the workload management architecture, this should meanwhile be reasonably easy to realize.

**Comment by reckart** [comment]
@GiantEnemyCrab The change is merged. If you have the opportunity to build from sources and try it out, please let me know.

**Comment by GiantEnemyCrab** [comment]
@reckart Thanks for the update on this!

I am able to build from source, and I was able to set annotator's document from COMPLETE to IN-PROGRESS from curation view. And I also could experience "leaving curation" when none of documents have COMPLETE status.

Also, I can toggle back and forth between CURATION-COMPLETE to CURATION-IN-PROGRESS from the curation view.

Those are working fine, and I have a question, because this request is for annotators individually be able to re-open documents from the annotation view. So I tried to do that but I couldn't find a way to do so. How could I set up such that annotator role can do so?

**Comment by reckart** [comment]
On the monitoring page (static workflow only), there is a new setting to allow annotators to re-open their documents from the annotation page. If you enable that setting and go to the annotation page, you should be able to toggle freely between finished and in-progress using the usual action bar button.

<img width="753" alt="Screenshot 2022-03-09 at 08 11 52" src="https://user-images.githubusercontent.com/1410238/157390820-7affa9f3-6ee0-4692-b0c9-34c549b9e2f5.png">

**Comment by GiantEnemyCrab** [comment]
Thank you for the guidance! I confirm this works!
One feedback I have is what if this checkbox goes to Project settings -> Annotation tab?
I am thinking that people will be able to locate this option more easily and I think "Annotation" tab is more intuitive.

**Comment by reckart** [comment]
The reason the checkbox is on the monitoring page is that users that have the "curator" but not the "manager" role can access it there - curators cannot access the project settings unless they are also managers.

**Comment by GiantEnemyCrab** [comment]
I see! Thanks for providing the explanation and that helps!
